#!/usr/bin/env python3
"""Run D8 story-first viewer session R1.

Creates viewer-record templates, imports only real viewer records, and keeps
external validation partial when no usable non-builder record exists.
"""

from __future__ import annotations

import csv
import datetime as dt
import hashlib
import json
import re
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[1]

TASKS = {
    "preflight": ("MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-PREFLIGHT", "outputs/main_citybrain_d8_story_first_viewer_session_preflight"),
    "template": ("MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-RECORD-TEMPLATE-R1", "outputs/main_citybrain_d8_story_first_viewer_record_template_r1"),
    "import": ("MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-RECORD-IMPORT-R2", "outputs/main_citybrain_d8_story_first_viewer_record_import_r2"),
    "scoreboard": ("MAIN-CITYBRAIN-D8-STORY-FIRST-NAIVE-VIEWER-SCOREBOARD-R3", "outputs/main_citybrain_d8_story_first_naive_viewer_scoreboard_r3"),
    "closeout": ("MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-VALIDATION-CLOSEOUT-R4", "outputs/main_citybrain_d8_story_first_viewer_validation_closeout_r4"),
    "handoff": ("MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-VALIDATION-CERTIFIED-STATE-HANDOFF-R5", "outputs/main_citybrain_d8_story_first_viewer_validation_certified_state_handoff_r5"),
}

INPUT_VIEWER_ROOT = REPO / "inputs" / "d8_story_first_viewer_records"
MANUAL_VIEWER_ROOT = REPO / "outputs" / "manual_d8_story_first_viewer_records"
MEDIA_MANIFEST = REPO / "inputs" / "d8_story_first_media" / "media_manifest.json"
MEDIA_HANDOFF = REPO / "outputs" / "main_citybrain_d8_story_first_capture_viewer_handoff_r4" / "STORY_FIRST_CAPTURE_VIEWER_HANDOFF_DECISION.json"
SCENARIO_FREEZE = REPO / "outputs" / "main_citybrain_d8_story_scenario_layer_milestone_freeze" / "STORY_SCENARIO_LAYER_MILESTONE_FREEZE_DECISION.json"
SCENARIO_LAYER = REPO / "packages" / "fixtures" / "story_first_demo" / "story_scenario_layer.json"

STORY_ID = "story:lon:wood_lane_ev_access_review"
SOURCE_RECORDS = ["TIMS-219173", "TIMS-210389", "EV asset 87"]
VIEWER_EXTS = {".json", ".jsonl", ".csv", ".md", ".txt"}

BOUNDARY = [
    "local/replay/review-only",
    "no action taken",
    "human review required",
    "proximity is not causality",
    "no EV asset blockage, unavailability, access-impact, operational-disruption, or causality claim",
    "no production/public API, dispatch, routing/control, enforcement, official ticket/case, legal/certified finding, or automated action",
]


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat()


def root(key: str) -> Path:
    return REPO / TASKS[key][1]


def rel(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_hash(root_path: Path) -> None:
    rows = []
    for path in sorted(root_path.rglob("*")):
        if path.is_file() and path.name != "HASH_MANIFEST.json":
            rows.append({"path": rel(path), "sha256": sha256(path), "bytes": path.stat().st_size})
    write_json(root_path / "HASH_MANIFEST.json", {"schema_version": "citybrain-hash-manifest-r1", "timestamp": now(), "file_count": len(rows), "files": rows})


def output_index(root_path: Path, title: str, artifacts: list[str]) -> None:
    write_text(root_path / "README.md", f"# {title}\n\nGenerated by `{rel(Path(__file__))}`.\n")
    lines = [f"# {title}", "", "## Artifacts", ""]
    lines.extend(f"- `{artifact}`" for artifact in artifacts)
    write_text(root_path / "LOCAL_OPEN_INDEX.md", "\n".join(lines) + "\n")


def input_row(path: Path) -> dict[str, Any]:
    return {"path": rel(path), "exists": path.exists(), "sha256": sha256(path) if path.exists() and path.is_file() else None}


def run_preflight() -> bool:
    root_path = root("preflight")
    root_path.mkdir(parents=True, exist_ok=True)
    freeze = read_json(SCENARIO_FREEZE) if SCENARIO_FREEZE.exists() else {}
    handoff = read_json(MEDIA_HANDOFF) if MEDIA_HANDOFF.exists() else {}
    manifest = read_json(MEDIA_MANIFEST) if MEDIA_MANIFEST.exists() else {}
    layer = read_json(SCENARIO_LAYER) if SCENARIO_LAYER.exists() else {}
    story_id = layer.get("scenario", {}).get("story_id")
    source_ids = layer.get("scenario", {}).get("source_record_ids", [])
    media_count = manifest.get("media_count") or handoff.get("media_count") or 0
    pass_gate = (
        freeze.get("status") == "PASS_MAIN_CITYBRAIN_D8_STORY_SCENARIO_LAYER_MILESTONE_FREEZE_WITH_LIMITATIONS"
        and handoff.get("status", "").startswith("PARTIAL_PENDING_VIEWER")
        and media_count >= 1
        and story_id == STORY_ID
        and "TIMS-219173" in source_ids
        and "TIMS-210389" in source_ids
        and "87" in source_ids
    )
    write_json(
        root_path / "VIEWER_SESSION_PREFLIGHT_DECISION.json",
        {
            "status": "PASS" if pass_gate else "PARTIAL_MEDIA_OR_UPSTREAM_MISSING",
            "task_name": TASKS["preflight"][0],
            "timestamp": now(),
            "scenario_freeze_status": freeze.get("status"),
            "media_handoff_status": handoff.get("status"),
            "media_count": media_count,
            "story_id": story_id,
            "source_records": source_ids,
        },
    )
    write_json(
        root_path / "VIEWER_SESSION_INPUT_INDEX.json",
        {
            "timestamp": now(),
            "scenario_freeze": input_row(SCENARIO_FREEZE),
            "media_handoff": input_row(MEDIA_HANDOFF),
            "media_manifest": input_row(MEDIA_MANIFEST),
            "scenario_layer": input_row(SCENARIO_LAYER),
            "viewer_input_root": {"path": rel(INPUT_VIEWER_ROOT), "exists": INPUT_VIEWER_ROOT.exists()},
            "manual_viewer_root": {"path": rel(MANUAL_VIEWER_ROOT), "exists": MANUAL_VIEWER_ROOT.exists()},
        },
    )
    output_index(root_path, TASKS["preflight"][0], ["VIEWER_SESSION_PREFLIGHT_DECISION.json", "VIEWER_SESSION_INPUT_INDEX.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return pass_gate


def run_template() -> None:
    INPUT_VIEWER_ROOT.mkdir(parents=True, exist_ok=True)
    root_path = root("template")
    root_path.mkdir(parents=True, exist_ok=True)
    readme = """# D8 Story-First Viewer Records

Use this folder for real viewer feedback only. Do not fill this from memory or as a placeholder.

Ask a non-builder viewer to watch the Wood Lane story-first capture or live page, then save one completed JSON or CSV row here.

Required story reminders:
- Wood Lane works near Scrubbs Lane / Wood Lane EV access asset.
- Proximity is not causality.
- No action has been taken.
- Human review is required.
"""
    template = {
        "viewer_id": "viewer_001",
        "viewer_type": "external_non_builder",
        "builder_involved": False,
        "viewed_media": "inputs/d8_story_first_media/wood_lane_story_title_and_boundary.png",
        "session_date": "YYYY-MM-DD",
        "understood_story_unaided": None,
        "story_summary_in_viewer_words": "",
        "identified_tension": "",
        "identified_surprise_moment": "",
        "boundary_understood": None,
        "boundary_summary_in_viewer_words": "",
        "confused_by": [],
        "would_show_to_stakeholder": None,
        "raw_notes": "",
    }
    csv_header = ",".join(template.keys()) + "\n"
    write_text(INPUT_VIEWER_ROOT / "README.md", readme)
    write_json(INPUT_VIEWER_ROOT / "viewer_record_template.json", template)
    write_text(INPUT_VIEWER_ROOT / "viewer_sessions_template.csv", csv_header)
    template_files = [INPUT_VIEWER_ROOT / "README.md", INPUT_VIEWER_ROOT / "viewer_record_template.json", INPUT_VIEWER_ROOT / "viewer_sessions_template.csv"]
    write_json(
        root_path / "VIEWER_RECORD_TEMPLATE_R1_DECISION.json",
        {
            "status": "PASS",
            "task_name": TASKS["template"][0],
            "timestamp": now(),
            "template_files": [rel(path) for path in template_files],
            "completed_viewer_record_created": False,
        },
    )
    write_json(root_path / "TEMPLATE_FILE_INDEX.json", [{"path": rel(path), "sha256": sha256(path), "bytes": path.stat().st_size} for path in template_files])
    output_index(root_path, TASKS["template"][0], ["VIEWER_RECORD_TEMPLATE_R1_DECISION.json", "TEMPLATE_FILE_INDEX.json", "HASH_MANIFEST.json"])
    write_hash(root_path)


def is_template_or_placeholder(path: Path, record: dict[str, Any] | None = None) -> bool:
    name = path.name.lower()
    if "template" in name or name == "readme.md":
        return True
    if record:
        if record.get("understood_story_unaided") is None and not record.get("story_summary_in_viewer_words"):
            return True
        if str(record.get("session_date", "")).upper() == "YYYY-MM-DD":
            return True
    return False


def parse_json_records(path: Path) -> list[dict[str, Any]]:
    payload = read_json(path)
    if isinstance(payload, list):
        return [row for row in payload if isinstance(row, dict)]
    if isinstance(payload, dict) and isinstance(payload.get("viewers"), list):
        return [row for row in payload["viewers"] if isinstance(row, dict)]
    if isinstance(payload, dict):
        return [payload]
    return []


def parse_jsonl_records(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def parse_csv_records(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def parse_text_record(path: Path) -> list[dict[str, Any]]:
    text = path.read_text(encoding="utf-8", errors="ignore").strip()
    if not text:
        return []
    return [{"viewer_id": path.stem, "viewer_type": "unknown_text_record", "raw_notes": text, "source_file": rel(path)}]


def discover_viewer_files() -> list[Path]:
    files = []
    for folder in [INPUT_VIEWER_ROOT, MANUAL_VIEWER_ROOT]:
        if folder.exists():
            files.extend(path for path in folder.rglob("*") if path.is_file() and path.suffix.lower() in VIEWER_EXTS)
    return sorted(set(files))


def parse_viewer_file(path: Path) -> list[dict[str, Any]]:
    suffix = path.suffix.lower()
    if suffix == ".json":
        return parse_json_records(path)
    if suffix == ".jsonl":
        return parse_jsonl_records(path)
    if suffix == ".csv":
        return parse_csv_records(path)
    return parse_text_record(path)


def classify_record(record: dict[str, Any], path: Path) -> tuple[str, list[str]]:
    if is_template_or_placeholder(path, record):
        return "placeholder_or_template", ["template_or_placeholder"]
    required = [
        "viewer_id",
        "viewer_type",
        "viewed_media",
        "session_date",
        "understood_story_unaided",
        "story_summary_in_viewer_words",
        "identified_tension",
        "identified_surprise_moment",
        "boundary_understood",
        "confused_by",
    ]
    missing = [key for key in required if key not in record or record.get(key) in (None, "")]
    if missing:
        return "incomplete", missing
    viewer_type = str(record.get("viewer_type", "")).lower()
    builder_involved = bool(record.get("builder_involved"))
    if viewer_type in {"external_non_builder", "non_builder", "external", "stakeholder_non_builder"} and not builder_involved:
        return "usable_non_builder", []
    return "usable_internal", []


def run_import() -> tuple[list[dict[str, Any]], list[dict[str, Any]], str]:
    root_path = root("import")
    root_path.mkdir(parents=True, exist_ok=True)
    ledger = []
    usable = []
    rejected = []
    for path in discover_viewer_files():
        try:
            parsed = parse_viewer_file(path)
        except Exception as exc:  # noqa: BLE001
            rejected.append({"source_file": rel(path), "classification": "parse_error", "reason": str(exc)})
            continue
        if not parsed and is_template_or_placeholder(path):
            rejected.append({"source_file": rel(path), "classification": "placeholder_or_template", "reason": "template/readme file"})
            continue
        for idx, record in enumerate(parsed, start=1):
            record = dict(record)
            record.setdefault("source_file", rel(path))
            classification, issues = classify_record(record, path)
            row = {
                "source_file": rel(path),
                "record_index": idx,
                "viewer_id": record.get("viewer_id"),
                "classification": classification,
                "issues": issues,
            }
            ledger.append(row)
            if classification in {"usable_non_builder", "usable_internal"}:
                usable.append({**record, "classification": classification})
            else:
                rejected.append({**row, "record": record})
    status = "PASS_WITH_LIMITATIONS" if usable else "PARTIAL_PENDING_VIEWER_RECORDS"
    write_json(root_path / "VIEWER_RECORD_IMPORT_R2_DECISION.json", {"status": status, "task_name": TASKS["import"][0], "timestamp": now(), "usable_viewer_count": len(usable), "usable_non_builder_count": len([r for r in usable if r["classification"] == "usable_non_builder"]), "rejected_count": len(rejected)})
    write_json(root_path / "VIEWER_RECORD_IMPORT_LEDGER.json", ledger)
    write_json(root_path / "USABLE_VIEWER_RECORDS.json", usable)
    write_json(root_path / "REJECTED_VIEWER_RECORDS.json", rejected)
    output_index(root_path, TASKS["import"][0], ["VIEWER_RECORD_IMPORT_R2_DECISION.json", "VIEWER_RECORD_IMPORT_LEDGER.json", "USABLE_VIEWER_RECORDS.json", "REJECTED_VIEWER_RECORDS.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return usable, rejected, status


def truthy(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "yes", "1", "y"}


def score_record(record: dict[str, Any]) -> dict[str, Any]:
    text = " ".join(str(record.get(key, "")) for key in ["story_summary_in_viewer_words", "identified_tension", "identified_surprise_moment", "boundary_summary_in_viewer_words", "raw_notes"]).lower()
    confusion = record.get("confused_by", [])
    if isinstance(confusion, str):
        confusion_items = [item.strip() for item in confusion.split(";") if item.strip()]
    else:
        confusion_items = list(confusion or [])
    serious_gap = any(term in text for term in ["charger blocked", "charger unavailable", "citybrain dispatched", "route executed", "official finding"])
    return {
        "viewer_id": record.get("viewer_id"),
        "viewer_classification": record.get("classification"),
        "story_understood_unaided": truthy(record.get("understood_story_unaided")),
        "tension_identified": bool(record.get("identified_tension")),
        "source_records_understood_as_evidence_context": any(term in text for term in ["tims", "record", "source", "evidence", "asset 87", "ev asset"]),
        "surprise_or_intelligence_moment_identified": bool(record.get("identified_surprise_moment")),
        "review_only_boundary_understood": truthy(record.get("boundary_understood")) or "review" in text,
        "no_action_boundary_understood": "no action" in text or "not executed" in text or truthy(record.get("boundary_understood")),
        "confusion_count": len(confusion_items),
        "viewer_validation_outcome": "PARTIAL_VIEWER_COMPREHENSION_GAP" if serious_gap else "PASS_VIEWER_COMPREHENSION_WITH_LIMITATIONS",
    }


def run_scoreboard(usable: list[dict[str, Any]]) -> str:
    root_path = root("scoreboard")
    root_path.mkdir(parents=True, exist_ok=True)
    scores = [score_record(record) for record in usable]
    serious = [score for score in scores if score["viewer_validation_outcome"] == "PARTIAL_VIEWER_COMPREHENSION_GAP"]
    status = "PARTIAL_PENDING_VIEWER_RECORDS" if not scores else ("PARTIAL_VIEWER_COMPREHENSION_GAP" if serious else "PASS_WITH_LIMITATIONS")
    write_json(root_path / "NAIVE_VIEWER_SCOREBOARD_R3.json", {"status": status, "viewer_count": len(scores), "scores": scores})
    write_json(root_path / "VIEWER_CONFUSION_LEDGER_R3.json", {"status": status, "confusions": [{"viewer_id": record.get("viewer_id"), "confused_by": record.get("confused_by", [])} for record in usable if record.get("confused_by")]})
    write_text(
        root_path / "VIEWER_QUOTES_SUMMARY.md",
        "# Viewer Quotes Summary\n\n"
        + ("No usable viewer records were available, so there are no viewer paraphrases to summarize.\n" if not usable else "Viewer records imported. This summary intentionally paraphrases and does not overquote.\n"),
    )
    write_json(root_path / "VIEWER_SCOREBOARD_R3_DECISION.json", {"status": status, "task_name": TASKS["scoreboard"][0], "timestamp": now(), "viewer_count": len(scores)})
    output_index(root_path, TASKS["scoreboard"][0], ["NAIVE_VIEWER_SCOREBOARD_R3.json", "VIEWER_CONFUSION_LEDGER_R3.json", "VIEWER_QUOTES_SUMMARY.md", "VIEWER_SCOREBOARD_R3_DECISION.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status


def secret_audit(root_path: Path) -> dict[str, Any]:
    patterns = [
        re.compile(r"AKIA[0-9A-Z]{16}"),
        re.compile(r"(?i)(api[_-]?key|secret|token)\s*[:=]\s*[A-Za-z0-9_\-]{20,}"),
        re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    ]
    hits = []
    for path in root_path.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if any(pattern.search(text) for pattern in patterns):
            hits.append(rel(path))
    return {"status": "PASS" if not hits else "FAIL", "secret_like_hits": hits}


def final_status(usable: list[dict[str, Any]], scoreboard_status: str) -> tuple[str, str]:
    if not usable:
        return (
            "PARTIAL_PENDING_VIEWER_RECORDS",
            "PARTIAL_PENDING_VIEWER_RECORDS_MAIN_CITYBRAIN_D8_STORY_FIRST_VIEWER_VALIDATION_CERTIFIED_STATE_HANDOFF",
        )
    non_builder = [record for record in usable if record.get("classification") == "usable_non_builder"]
    if not non_builder:
        return (
            "PARTIAL_INTERNAL_VIEWER_ONLY",
            "PARTIAL_INTERNAL_VIEWER_ONLY_MAIN_CITYBRAIN_D8_STORY_FIRST_VIEWER_VALIDATION_CERTIFIED_STATE_HANDOFF",
        )
    if scoreboard_status == "PARTIAL_VIEWER_COMPREHENSION_GAP":
        return (
            "PARTIAL_VIEWER_COMPREHENSION_GAP",
            "PARTIAL_VIEWER_COMPREHENSION_GAP_MAIN_CITYBRAIN_D8_STORY_FIRST_VIEWER_VALIDATION_CERTIFIED_STATE_HANDOFF",
        )
    return (
        "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_VIEWER_VALIDATION_CLOSEOUT_WITH_LIMITATIONS",
        "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_VIEWER_VALIDATION_CERTIFIED_STATE_HANDOFF_WITH_LIMITATIONS",
    )


def run_closeout(usable: list[dict[str, Any]], rejected: list[dict[str, Any]], import_status: str, scoreboard_status: str) -> str:
    root_path = root("closeout")
    root_path.mkdir(parents=True, exist_ok=True)
    closeout_status, _ = final_status(usable, scoreboard_status)
    media = read_json(MEDIA_MANIFEST) if MEDIA_MANIFEST.exists() else {}
    write_json(
        root_path / "STORY_FIRST_VIEWER_VALIDATION_CLOSEOUT_DECISION.json",
        {
            "status": closeout_status,
            "task_name": TASKS["closeout"][0],
            "timestamp": now(),
            "media_count": media.get("media_count", 0),
            "usable_viewer_count": len(usable),
            "usable_non_builder_count": len([r for r in usable if r.get("classification") == "usable_non_builder"]),
            "rejected_viewer_record_count": len(rejected),
            "viewer_import_status": import_status,
            "scoreboard_status": scoreboard_status,
            "external_validation_claimed": bool([r for r in usable if r.get("classification") == "usable_non_builder"]),
        },
    )
    write_json(root_path / "CLAIM_BOUNDARY_AUDIT.json", {"status": "PASS", "boundary": BOUNDARY})
    write_json(root_path / "NO_ACTION_AUDIT.json", {"status": "PASS", "execution_state": "not_executed_only", "actions_created": 0})
    write_json(root_path / "NO_MUTATION_AUDIT.json", {"status": "PASS", "upstream_outputs_mutated": False, "created_templates": True})
    write_json(root_path / "SECRET_AUDIT.json", secret_audit(root_path))
    write_text(
        root_path / "OPEN_GAPS_AND_NEXT_ACTIONS.md",
        "# Open Gaps And Next Actions\n\n"
        + ("- Add at least one completed non-builder viewer record under `inputs/d8_story_first_viewer_records/`.\n" if not usable else "")
        + "- Keep the story framed as proximity-not-causality and human-review-only.\n",
    )
    output_index(root_path, TASKS["closeout"][0], ["STORY_FIRST_VIEWER_VALIDATION_CLOSEOUT_DECISION.json", "CLAIM_BOUNDARY_AUDIT.json", "NO_ACTION_AUDIT.json", "NO_MUTATION_AUDIT.json", "SECRET_AUDIT.json", "OPEN_GAPS_AND_NEXT_ACTIONS.md", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return closeout_status


def run_handoff(usable: list[dict[str, Any]], scoreboard_status: str, closeout_status: str) -> str:
    root_path = root("handoff")
    root_path.mkdir(parents=True, exist_ok=True)
    _, handoff_status = final_status(usable, scoreboard_status)
    media = read_json(MEDIA_MANIFEST) if MEDIA_MANIFEST.exists() else {}
    non_builder_count = len([r for r in usable if r.get("classification") == "usable_non_builder"])
    write_json(
        root_path / "STORY_FIRST_VIEWER_VALIDATION_CERTIFIED_STATE_HANDOFF_DECISION.json",
        {
            "status": handoff_status,
            "task_name": TASKS["handoff"][0],
            "timestamp": now(),
            "closeout_status": closeout_status,
            "story_id": STORY_ID,
            "source_records": SOURCE_RECORDS,
            "media_count": media.get("media_count", 0),
            "usable_viewer_count": len(usable),
            "external_non_builder_viewer_count": non_builder_count,
            "comprehension_summary": scoreboard_status,
            "external_demo_sharing_go_no_go": "GO_WITH_LIMITATIONS" if handoff_status.startswith("PASS_") else "NO_GO_VIEWER_RECORDS_PENDING",
            "remaining_limitations": [
                "No external viewer validation is claimed until a usable non-builder viewer record is imported and scored.",
                "No EV asset blockage, unavailability, impact, or causality claim.",
                "No action, dispatch, routing/control, enforcement, official ticket/case, legal/certified finding, production/public API, or automated action.",
            ],
            "recommended_next_task": "MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-IMPORT-R2" if not usable else "MAIN-CITYBRAIN-D8-STORY-FIRST-DEMO-EXTERNAL-SHARE-READINESS-R1",
        },
    )
    write_text(
        root_path / "CURRENT_STORY_FIRST_VIEWER_VALIDATION_STATE.md",
        "# Current Story-First Viewer Validation State\n\n"
        f"Status: `{handoff_status}`\n\n"
        f"Media count: {media.get('media_count', 0)}\n\n"
        f"Usable viewer records: {len(usable)}\n\n"
        f"External/non-builder viewer records: {non_builder_count}\n\n"
        "Viewer templates are available under `inputs/d8_story_first_viewer_records/`.\n",
    )
    write_json(
        root_path / "READY_NEXT_TRACKS.json",
        {
            "ready": ["MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-IMPORT-R2"],
            "blocked": ["external demo sharing"] if not handoff_status.startswith("PASS_") else [],
        },
    )
    write_json(
        root_path / "DEFERRED_NOT_CLAIMED_LEDGER.json",
        {
            "not_claimed": [
                "external naive-viewer validation" if not handoff_status.startswith("PASS_") else None,
                "EV asset blocked/unavailable/impacted",
                "dispatch/routing/control/enforcement/official case/legal-certified/action",
            ],
            "boundary": BOUNDARY,
        },
    )
    output_index(root_path, TASKS["handoff"][0], ["STORY_FIRST_VIEWER_VALIDATION_CERTIFIED_STATE_HANDOFF_DECISION.json", "CURRENT_STORY_FIRST_VIEWER_VALIDATION_STATE.md", "READY_NEXT_TRACKS.json", "DEFERRED_NOT_CLAIMED_LEDGER.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return handoff_status


def main() -> int:
    for _, path in TASKS.values():
        (REPO / path).mkdir(parents=True, exist_ok=True)
    run_preflight()
    run_template()
    usable, rejected, import_status = run_import()
    scoreboard_status = run_scoreboard(usable)
    closeout_status = run_closeout(usable, rejected, import_status, scoreboard_status)
    handoff_status = run_handoff(usable, scoreboard_status, closeout_status)
    print(json.dumps({"status": handoff_status, "usable_viewer_count": len(usable), "output_root": rel(root("handoff"))}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
