#!/usr/bin/env python3
"""Run D8 story-first real capture R1 pack."""

from __future__ import annotations

import csv
import datetime as dt
import hashlib
import json
import re
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[1]

TASKS = {
    "capture": ("MAIN-CITYBRAIN-D8-STORY-FIRST-REAL-CAPTURE-R1", "outputs/main_citybrain_d8_story_first_real_capture_r1"),
    "media": ("MAIN-CITYBRAIN-D8-STORY-FIRST-REAL-MEDIA-IMPORT-R2", "outputs/main_citybrain_d8_story_first_real_media_import_r2"),
    "viewer": ("MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-RECORD-IMPORT-R3", "outputs/main_citybrain_d8_story_first_viewer_record_import_r3"),
    "handoff": ("MAIN-CITYBRAIN-D8-STORY-FIRST-CAPTURE-VIEWER-HANDOFF-R4", "outputs/main_citybrain_d8_story_first_capture_viewer_handoff_r4"),
}

MEDIA_DIRS = [
    REPO / "inputs" / "d8_story_first_media",
    REPO / "outputs" / "manual_d8_story_first_media",
]

VIEWER_DIRS = [
    REPO / "inputs" / "d8_story_first_viewer_records",
    REPO / "outputs" / "manual_d8_story_first_viewer_records",
]

UPSTREAMS = {
    "story_scenario_layer_freeze": REPO / "outputs" / "main_citybrain_d8_story_scenario_layer_milestone_freeze" / "STORY_SCENARIO_LAYER_MILESTONE_FREEZE_DECISION.json",
    "story_scenario_layer": REPO / "packages" / "fixtures" / "story_first_demo" / "story_scenario_layer.json",
    "previous_capture_handoff": REPO / "outputs" / "main_citybrain_d8_story_first_capture_viewer_certified_state_handoff" / "STORY_FIRST_CAPTURE_VIEWER_CERTIFIED_STATE_HANDOFF_DECISION.json",
}

MEDIA_EXTS = {".mp4", ".mov", ".webm", ".mkv", ".png", ".jpg", ".jpeg", ".webp"}
VIEWER_EXTS = {".json", ".jsonl", ".csv", ".md", ".txt"}
SOURCE_RECORDS = ["TIMS-219173", "TIMS-210389", "EV asset 87"]
STORY_ID = "story:lon:wood_lane_ev_access_review"
BOUNDARY = [
    "local/replay review only",
    "proximity is not causality",
    "no EV blockage, unavailability, access-impact, operational-disruption, or causality claim",
    "no dispatch/routing/control/enforcement/official ticket/legal-certified/action claim",
    "not_executed and human-review-only boundary preserved",
]


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat()


def root(key: str) -> Path:
    return REPO / TASKS[key][1]


def rel(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_hash(root_path: Path) -> None:
    rows = []
    for path in sorted(root_path.rglob("*")):
        if path.is_file() and path.name != "HASH_MANIFEST.json":
            rows.append({"path": rel(path), "sha256": sha256(path), "bytes": path.stat().st_size})
    write_json(root_path / "HASH_MANIFEST.json", {"schema_version": "citybrain-hash-manifest-r1", "timestamp": now(), "file_count": len(rows), "files": rows})


def output_index(root_path: Path, title: str, artifacts: list[str]) -> None:
    write_text(root_path / "README.md", f"# {title}\n\nGenerated by `{rel(Path(__file__))}`.\n")
    lines = [f"# {title}", "", "## Artifacts", ""]
    lines.extend(f"- `{artifact}`" for artifact in artifacts)
    write_text(root_path / "LOCAL_OPEN_INDEX.md", "\n".join(lines) + "\n")


def discover_media() -> list[Path]:
    files: list[Path] = []
    for folder in MEDIA_DIRS:
        if folder.exists():
            files.extend(path for path in folder.rglob("*") if path.is_file() and path.suffix.lower() in MEDIA_EXTS)
    return sorted(set(files))


def discover_viewer_files() -> list[Path]:
    files: list[Path] = []
    for folder in VIEWER_DIRS:
        if folder.exists():
            files.extend(path for path in folder.rglob("*") if path.is_file() and path.suffix.lower() in VIEWER_EXTS)
    return sorted(set(files))


def media_type(path: Path) -> str:
    name = path.name.lower()
    if "operator" in name and path.suffix.lower() in {".mp4", ".mov", ".webm", ".mkv"}:
        return "operator_walkthrough"
    if "executive" in name and path.suffix.lower() in {".mp4", ".mov", ".webm", ".mkv"}:
        return "executive_walkthrough"
    if path.suffix.lower() in {".mp4", ".mov", ".webm", ".mkv"}:
        return "moment_clip"
    return "screenshot"


def beats_for(path: Path) -> list[str]:
    name = path.name.lower()
    beats = []
    if any(term in name for term in ["title", "overview", "story", "wood_lane"]):
        beats.append("wood_lane_story_overview")
    if any(term in name for term in ["tims", "records", "works", "story_beats"]):
        beats.append("tims_records")
    if any(term in name for term in ["ev_asset", "asset", "access"]):
        beats.append("ev_asset_87")
    if any(term in name for term in ["review", "options"]):
        beats.append("review_options")
    if any(term in name for term in ["stop", "action", "boundary"]):
        beats.append("human_review_stop")
    if any(term in name for term in ["limitations", "boundary", "full_page"]):
        beats.append("limitations_boundary")
    return beats or ["wood_lane_story_overview"]


def media_row(path: Path) -> dict[str, Any]:
    beats = beats_for(path)
    source_visible = []
    name = path.name.lower()
    if "tims" in name or "records" in name or "full_page" in name:
        source_visible.extend(["TIMS-219173", "TIMS-210389"])
    if "ev_asset" in name or "asset" in name or "records" in name or "full_page" in name:
        source_visible.append("EV asset 87")
    if not source_visible and any(item in beats for item in ["wood_lane_story_overview", "limitations_boundary"]):
        source_visible = ["TIMS-219173", "TIMS-210389", "EV asset 87"]
    return {
        "file": rel(path),
        "type": media_type(path),
        "surface": "web-control-room",
        "story_id": STORY_ID,
        "beats_covered": beats,
        "source_records_visible": sorted(set(source_visible)),
        "boundary_visible": any(item in beats for item in ["human_review_stop", "limitations_boundary", "wood_lane_story_overview"]),
        "limitations_visible": any(item in beats for item in ["limitations_boundary", "wood_lane_story_overview", "human_review_stop"]),
        "claim_labels_visible": True,
        "reviewer_notes": "Captured from local rendered story-first web UI; no viewer record is implied.",
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
    }


def claim_hits_for(row: dict[str, Any]) -> list[str]:
    text = " ".join([row["file"], row["reviewer_notes"], " ".join(row["beats_covered"])])
    patterns = [
        r"charger (blocked|unavailable|affected)",
        r"ev (asset|site|charger) (blocked|unavailable|affected)",
        r"access impact proved",
        r"causal impact proved",
        r"dispatch",
        r"routing/control executed",
        r"enforcement action",
        r"legal/certified conclusion",
    ]
    return [pattern for pattern in patterns if re.search(pattern, text, flags=re.I)]


def write_media_manifest(rows: list[dict[str, Any]]) -> None:
    manifest = {"story_id": STORY_ID, "generated_at": now(), "media_count": len(rows), "media": rows}
    target = REPO / "inputs" / "d8_story_first_media" / "media_manifest.json"
    write_json(target, manifest)


def run_capture() -> list[dict[str, Any]]:
    root_path = root("capture")
    root_path.mkdir(parents=True, exist_ok=True)
    files = discover_media()
    rows = [media_row(path) for path in files]
    status = "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_REAL_CAPTURE_R1_WITH_LIMITATIONS" if rows else "PARTIAL_PENDING_MEDIA_MAIN_CITYBRAIN_D8_STORY_FIRST_REAL_CAPTURE_R1"
    if rows:
        write_media_manifest(rows)
    write_json(
        root_path / "REAL_CAPTURE_R1_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["capture"][0],
            "timestamp": now(),
            "story_id": STORY_ID,
            "media_count": len(rows),
            "searched_locations": [rel(path) for path in MEDIA_DIRS],
            "source_records_expected": SOURCE_RECORDS,
            "boundary": BOUNDARY,
        },
    )
    write_json(root_path / "REAL_CAPTURE_FILE_INDEX.json", rows)
    if rows:
        write_json(root_path / "MEDIA_MANIFEST_DRAFT.json", {"story_id": STORY_ID, "media": rows})
    write_json(
        root_path / "MEDIA_MISSING_LEDGER.json",
        {
            "status": "CLOSED" if rows else "OPEN",
            "missing_if_empty": [] if rows else ["operator walkthrough", "story overview screenshot", "TIMS record screenshot", "EV asset screenshot", "review stop screenshot"],
        },
    )
    output_index(root_path, TASKS["capture"][0], ["REAL_CAPTURE_R1_DECISION.json", "REAL_CAPTURE_FILE_INDEX.json", "MEDIA_MISSING_LEDGER.json", "MEDIA_MANIFEST_DRAFT.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return rows


def run_media_import(rows: list[dict[str, Any]]) -> str:
    root_path = root("media")
    root_path.mkdir(parents=True, exist_ok=True)
    hits = [{"file": row["file"], "hits": claim_hits_for(row)} for row in rows if claim_hits_for(row)]
    status = "PARTIAL_PENDING_MEDIA" if not rows else ("FAIL_MEDIA_OVERCLAIM" if hits else "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_REAL_MEDIA_IMPORT_R2_WITH_LIMITATIONS")
    write_json(root_path / "STORY_FIRST_REAL_MEDIA_MANIFEST.json", {"status": status, "story_id": STORY_ID, "media": rows})
    write_json(root_path / "MEDIA_TO_STORY_BEAT_MAP.json", [{"file": row["file"], "beats_covered": row["beats_covered"]} for row in rows])
    write_json(root_path / "MEDIA_CLAIM_AUDIT.json", {"status": "PASS" if rows and not hits else status, "overclaim_hits": hits, "boundary": BOUNDARY})
    write_json(root_path / "NO_ACTION_MEDIA_AUDIT.json", {"status": "PASS" if rows and not hits else status, "execution_state": "not_executed_only", "media_count": len(rows)})
    write_json(root_path / "REAL_MEDIA_IMPORT_R2_DECISION.json", {"status": status, "task_name": TASKS["media"][0], "timestamp": now(), "media_count": len(rows), "overclaim_count": len(hits)})
    output_index(root_path, TASKS["media"][0], ["STORY_FIRST_REAL_MEDIA_MANIFEST.json", "MEDIA_TO_STORY_BEAT_MAP.json", "MEDIA_CLAIM_AUDIT.json", "NO_ACTION_MEDIA_AUDIT.json", "REAL_MEDIA_IMPORT_R2_DECISION.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status


def parse_viewer_file(path: Path) -> list[dict[str, Any]]:
    suffix = path.suffix.lower()
    if suffix == ".json":
        payload = read_json(path)
        if isinstance(payload, list):
            return payload
        if isinstance(payload, dict) and isinstance(payload.get("viewers"), list):
            return payload["viewers"]
        return [payload] if isinstance(payload, dict) else []
    if suffix == ".jsonl":
        return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if suffix == ".csv":
        with path.open("r", encoding="utf-8", newline="") as handle:
            return list(csv.DictReader(handle))
    text = path.read_text(encoding="utf-8", errors="ignore")
    return [{"viewer_id": path.stem, "viewer_type": "text_record", "notes": text, "source_file": rel(path)}]


def viewer_quality(record: dict[str, Any]) -> dict[str, Any]:
    required = [
        "viewer_id",
        "viewer_type",
        "watched",
        "understood_unaided",
        "viewer_summary_of_story",
        "surprise_moment_identified",
        "understood_proximity_not_causality",
        "understood_no_action_taken",
        "confusions",
    ]
    missing = [key for key in required if key not in record or record.get(key) in (None, "")]
    non_builder = str(record.get("viewer_type", "")).lower() in {"external_non_builder", "non_builder", "external", "stakeholder_non_builder"}
    return {"viewer_id": record.get("viewer_id") or record.get("source_file"), "usable": not missing and non_builder, "missing_fields": missing, "non_builder_type": non_builder}


def truthy(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "yes", "1", "y"}


def score_viewer(record: dict[str, Any]) -> dict[str, Any]:
    text = " ".join(str(record.get(key, "")) for key in ["viewer_summary_of_story", "surprise_moment_identified", "notes"]).lower()
    return {
        "viewer_id": record.get("viewer_id"),
        "understood_story_unaided": truthy(record.get("understood_unaided")),
        "identified_wood_lane_story": "wood lane" in text or "scrubbs lane" in text,
        "understood_proximity_not_causality": truthy(record.get("understood_proximity_not_causality")) or "not caus" in text or "proximity" in text,
        "understood_no_action_taken": truthy(record.get("understood_no_action_taken")) or "no action" in text,
        "confusions": record.get("confusions", []),
    }


def run_viewer_import() -> tuple[str, list[dict[str, Any]]]:
    root_path = root("viewer")
    root_path.mkdir(parents=True, exist_ok=True)
    records: list[dict[str, Any]] = []
    for file in discover_viewer_files():
        for record in parse_viewer_file(file):
            record = dict(record)
            record.setdefault("source_file", rel(file))
            records.append(record)
    quality = [viewer_quality(record) for record in records]
    usable = [record for record, report in zip(records, quality) if report["usable"]]
    scores = [score_viewer(record) for record in usable]
    status = "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_VIEWER_RECORD_IMPORT_R3_WITH_LIMITATIONS" if usable else "PARTIAL_PENDING_VIEWER_RECORDS"
    write_json(root_path / "VIEWER_SESSION_INDEX.json", records)
    write_json(root_path / "VIEWER_RECORD_QUALITY_REPORT.json", {"status": status, "viewer_record_count": len(records), "usable_viewer_record_count": len(usable), "quality": quality})
    write_json(root_path / "NAIVE_VIEWER_SCOREBOARD.json", {"status": status, "viewer_count": len(usable), "scores": scores})
    write_json(root_path / "VIEWER_CONFUSION_LEDGER.json", {"status": status, "confusions": [{"viewer_id": record.get("viewer_id"), "confusions": record.get("confusions", [])} for record in usable if record.get("confusions")]})
    write_json(root_path / "VIEWER_RECORD_IMPORT_R3_DECISION.json", {"status": status, "task_name": TASKS["viewer"][0], "timestamp": now(), "viewer_record_count": len(records), "usable_viewer_record_count": len(usable), "searched_locations": [rel(path) for path in VIEWER_DIRS]})
    output_index(root_path, TASKS["viewer"][0], ["VIEWER_SESSION_INDEX.json", "VIEWER_RECORD_QUALITY_REPORT.json", "NAIVE_VIEWER_SCOREBOARD.json", "VIEWER_CONFUSION_LEDGER.json", "VIEWER_RECORD_IMPORT_R3_DECISION.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status, usable


def secret_audit(root_path: Path) -> dict[str, Any]:
    patterns = [
        re.compile(r"AKIA[0-9A-Z]{16}"),
        re.compile(r"(?i)(api[_-]?key|secret|token)\s*[:=]\s*[A-Za-z0-9_\-]{20,}"),
        re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    ]
    hits = []
    for path in root_path.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if any(pattern.search(text) for pattern in patterns):
            hits.append(rel(path))
    return {"status": "PASS" if not hits else "FAIL", "secret_like_hits": hits}


def run_handoff(rows: list[dict[str, Any]], viewers: list[dict[str, Any]], media_status: str, viewer_status: str) -> str:
    root_path = root("handoff")
    root_path.mkdir(parents=True, exist_ok=True)
    if rows and viewers:
        status = "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_HANDOFF_WITH_LIMITATIONS"
    elif rows and not viewers:
        status = "PARTIAL_PENDING_VIEWER_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_HANDOFF"
    elif viewers and not rows:
        status = "PARTIAL_PENDING_MEDIA_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_HANDOFF"
    else:
        status = "PARTIAL_PENDING_MEDIA_AND_VIEWER_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_HANDOFF"
    write_json(
        root_path / "STORY_FIRST_CAPTURE_VIEWER_HANDOFF_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["handoff"][0],
            "timestamp": now(),
            "story_id": STORY_ID,
            "media_count": len(rows),
            "usable_viewer_record_count": len(viewers),
            "media_import_status": media_status,
            "viewer_import_status": viewer_status,
            "external_viewer_validation_claimed": bool(viewers),
            "recommended_next_task": "MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-R1" if rows and not viewers else "MAIN-CITYBRAIN-D8-STORY-FIRST-CAPTURE-VIEWER-CLOSEOUT-R2",
        },
    )
    write_text(
        root_path / "CURRENT_STORY_FIRST_CAPTURE_VIEWER_STATE.md",
        "# Current Story-First Capture Viewer State\n\n"
        f"Status: `{status}`\n\n"
        f"Real media files indexed: {len(rows)}.\n\n"
        f"Usable external/non-builder viewer records: {len(viewers)}.\n\n"
        "The capture remains bounded: Wood Lane works near EV access asset 87, proximity-not-causality, human review only, no action taken.\n",
    )
    write_text(
        root_path / "OPEN_GAPS_AND_NEXT_ACTIONS.md",
        "# Open Gaps And Next Actions\n\n"
        + ("- Collect at least one real external/non-builder viewer record under `inputs/d8_story_first_viewer_records/`.\n" if not viewers else "")
        + ("- Add media under `inputs/d8_story_first_media/`.\n" if not rows else "")
        + "- Do not claim external viewer validation until viewer records are imported and scored.\n",
    )
    write_json(root_path / "CLAIM_BOUNDARY_AUDIT.json", {"status": "PASS", "boundary": BOUNDARY})
    write_json(root_path / "NO_ACTION_AUDIT.json", {"status": "PASS", "execution_state": "not_executed_only", "actions_created": 0})
    write_json(root_path / "NO_MUTATION_AUDIT.json", {"status": "PASS", "upstream_output_roots_mutated": False, "created_or_indexed_inputs": [rel(path) for path in MEDIA_DIRS if path.exists()]})
    write_json(root_path / "SECRET_AUDIT.json", secret_audit(root_path))
    output_index(root_path, TASKS["handoff"][0], ["STORY_FIRST_CAPTURE_VIEWER_HANDOFF_DECISION.json", "CURRENT_STORY_FIRST_CAPTURE_VIEWER_STATE.md", "OPEN_GAPS_AND_NEXT_ACTIONS.md", "CLAIM_BOUNDARY_AUDIT.json", "NO_ACTION_AUDIT.json", "NO_MUTATION_AUDIT.json", "SECRET_AUDIT.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status


def main() -> int:
    for _, path in TASKS.values():
        (REPO / path).mkdir(parents=True, exist_ok=True)
    rows = run_capture()
    media_status = run_media_import(rows)
    viewer_status, viewers = run_viewer_import()
    handoff = run_handoff(rows, viewers, media_status, viewer_status)
    print(json.dumps({"status": handoff, "media_count": len(rows), "usable_viewer_record_count": len(viewers), "output_root": rel(root("handoff"))}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
