#!/usr/bin/env python3
"""Run D8 story scenario-layer reconcile pack."""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import re
import subprocess
import zipfile
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[1]

TASKS = {
    "preflight": ("MAIN-CITYBRAIN-D8-STORY-SCENARIO-LAYER-PREFLIGHT", "outputs/main_citybrain_d8_story_scenario_layer_preflight"),
    "authoring": ("MAIN-CITYBRAIN-D8-WOOD-LANE-SCENARIO-AUTHORING-R1", "outputs/main_citybrain_d8_wood_lane_scenario_authoring_r1"),
    "evidence": ("MAIN-CITYBRAIN-D8-SCENARIO-TO-SOURCE-EVIDENCE-MAP-R2", "outputs/main_citybrain_d8_scenario_to_source_evidence_map_r2"),
    "options": ("MAIN-CITYBRAIN-D8-SCENARIO-REVIEW-OPTIONS-AND-BOUNDARY-R3", "outputs/main_citybrain_d8_scenario_review_options_and_boundary_r3"),
    "ui": ("MAIN-CITYBRAIN-D8-STORY-FIRST-UI-SCENARIO-BINDING-SMOKE-R4", "outputs/main_citybrain_d8_story_first_ui_scenario_binding_smoke_r4"),
    "closeout": ("MAIN-CITYBRAIN-D8-STORY-SCENARIO-LAYER-CLOSEOUT", "outputs/main_citybrain_d8_story_scenario_layer_closeout"),
    "freeze": ("MAIN-CITYBRAIN-D8-STORY-SCENARIO-LAYER-MILESTONE-FREEZE", "outputs/main_citybrain_d8_story_scenario_layer_milestone_freeze"),
}

INPUTS = {
    "probe_closeout": REPO / "outputs" / "main_citybrain_d8_story_probe_only_closeout" / "STORY_PROBE_ONLY_CLOSEOUT_DECISION.json",
    "probe_recommendation": REPO / "outputs" / "main_citybrain_d8_cross_source_story_candidate_selection_r2" / "SELECTED_STORY_RECOMMENDATION.json",
    "story_mining_decision": REPO / "outputs" / "main_citybrain_d8_story_mining_and_story_first_ui_redesign" / "MAIN_CITYBRAIN_D8_STORY_MINING_UI_REDESIGN_SEQUENCE_DECISION.json",
    "story_source_bundle": REPO / "packages" / "fixtures" / "story_first_demo" / "story_source_bundle.json",
    "story_scenario_fixture": REPO / "packages" / "fixtures" / "story_first_demo" / "story_scenario_layer.json",
    "web_runtime_loader": REPO / "apps" / "web-control-room" / "src" / "runtimeBundle.js",
    "web_story_view": REPO / "apps" / "web-control-room" / "src" / "views" / "storyFirst.js",
    "web_snapshot_renderer": REPO / "apps" / "web-control-room" / "src" / "renderSnapshot.mjs",
}

REQUIRED_SOURCE_IDS = ["TIMS-219173", "TIMS-210389", "87"]
FINAL_PASS = "PASS_MAIN_CITYBRAIN_D8_STORY_SCENARIO_LAYER_CLOSEOUT_WITH_LIMITATIONS"
FREEZE_PASS = "PASS_MAIN_CITYBRAIN_D8_STORY_SCENARIO_LAYER_MILESTONE_FREEZE_WITH_LIMITATIONS"
BOUNDARY = [
    "local/replay/review/query context only",
    "no production/public API/live monitoring",
    "no alerting, dispatch, routing/control, enforcement, official ticket/case",
    "no legal/certified finding",
    "no automated action",
    "no claim that the EV site is unavailable, blocked, or operationally affected",
    "proximity is a review heuristic, not causal impact",
]


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat()


def rel(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def root(key: str) -> Path:
    return REPO / TASKS[key][1]


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_hash(root_path: Path) -> None:
    rows = []
    for path in sorted(root_path.rglob("*")):
        if path.is_file() and path.name != "HASH_MANIFEST.json":
            rows.append({"path": rel(path), "sha256": sha256(path), "bytes": path.stat().st_size})
    write_json(
        root_path / "HASH_MANIFEST.json",
        {"schema_version": "citybrain-hash-manifest-r1", "timestamp": now(), "file_count": len(rows), "files": rows},
    )


def output_index(root_path: Path, title: str, artifacts: list[str]) -> None:
    write_text(root_path / "README.md", f"# {title}\n\nGenerated by `{rel(Path(__file__))}`.\n")
    lines = [f"# {title}", "", "## Artifacts", ""]
    lines.extend(f"- `{artifact}`" for artifact in artifacts)
    write_text(root_path / "LOCAL_OPEN_INDEX.md", "\n".join(lines) + "\n")


def web_hashes() -> dict[str, str]:
    files = [
        INPUTS["web_runtime_loader"],
        INPUTS["web_story_view"],
        INPUTS["web_snapshot_renderer"],
        REPO / "apps" / "web-control-room" / "src" / "renderApp.js",
        REPO / "apps" / "web-control-room" / "index.html",
        REPO / "apps" / "web-control-room" / "styles.css",
    ]
    return {rel(path): sha256(path) for path in files if path.exists()}


def story_bundle() -> dict[str, Any]:
    return read_json(INPUTS["story_source_bundle"])


def selected_story() -> dict[str, Any]:
    return story_bundle()["selected_story"]


def source_records_by_id() -> dict[str, dict[str, Any]]:
    return {str(record["source_record_id"]): record for record in selected_story()["records"]}


def status_for(record: dict[str, Any]) -> str:
    fields = record.get("fields", {})
    if record["source_record_id"].startswith("TIMS"):
        return f"{fields.get('status')} / {fields.get('severity')}; last modified {fields.get('last_modified')}"
    return f"{fields.get('rapid_charge_points')} rapid point(s); {fields.get('taxi_public_use')}"


def claim_boundary_audit(path: Path) -> dict[str, Any]:
    audit = {
        "status": "PASS",
        "timestamp": now(),
        "boundary": BOUNDARY,
        "forbidden_claims_present": False,
    }
    write_json(path, audit)
    return audit


def no_fact_invention_audit(path: Path, refs: list[str], limitations: list[str]) -> dict[str, Any]:
    missing = [ref for ref in refs if ref not in REQUIRED_SOURCE_IDS and not ref.startswith("limitation:")]
    audit = {
        "status": "PASS" if not missing and limitations else "FAIL",
        "timestamp": now(),
        "allowed_source_records": REQUIRED_SOURCE_IDS,
        "unexpected_refs": missing,
        "limitations_present": bool(limitations),
        "rule": "every viewer-facing claim must cite TIMS-219173, TIMS-210389, EV asset 87, or an explicit limitation",
    }
    write_json(path, audit)
    return audit


def make_scenario_layer() -> dict[str, Any]:
    story = selected_story()
    records = source_records_by_id()
    wood = records["TIMS-219173"]
    westway = records["TIMS-210389"]
    asset = records["87"]
    scenario = {
        "story_id": "story:lon:wood_lane_ev_access_review",
        "scenario_layer_validated": True,
        "scenario_layer_type": "bounded_review_premise_over_source_records",
        "city": "London",
        "scene_title": "Wood Lane works near a named rapid EV access asset",
        "place_or_corridor": "Wood Lane / Scrubbs Lane, Hammersmith & Fulham",
        "what_happened": "TfL source records describe active works on Wood Lane and Westway. A London Datastore source row identifies Scrubbs Lane - Wood Lane Car Park as a nearby rapid EV access asset.",
        "viewer_summary": "CityBrain connects Wood Lane works records with a nearby rapid EV access asset, then stops at review because proximity is a heuristic, not an impact finding.",
        "date_time_or_status": f"{status_for(wood)}; {status_for(westway)}",
        "source_records": REQUIRED_SOURCE_IDS,
        "source_record_ids": REQUIRED_SOURCE_IDS,
        "source_dataset_names": story["source_dataset_names"],
        "records": [wood, westway, asset],
        "evidence_links": story["evidence_links"],
        "primary_limitation": "Proximity is not impact; the scenario makes no EV availability, blockage, access-impact, or operational-disruption finding.",
        "review_only_boundary": "Local/replay/review/query context only. No alerts, dispatch, routing, enforcement, official ticket, legal/certified finding, approval, or automated action.",
        "why_this_is_non_obvious": "The useful intelligence beat is the bounded connection: road works records and access infrastructure context appear near each other, while the system refuses to overclaim what the sources do not prove.",
        "map_anchor": story["map_anchor"],
        "beats": [
            {
                "beat_id": "B01_WHAT_IS_HAPPENING_NOW",
                "title": "What is happening now: Wood Lane works record",
                "viewer_copy": wood["summary"],
                "source_record_ids": ["TIMS-219173"],
                "status_or_time": status_for(wood),
                "limitation": "Active works record, not live incident response or operational instruction.",
            },
            {
                "beat_id": "B02_NEARBY_ACCESS_ASSET",
                "title": "What nearby access asset is relevant",
                "viewer_copy": asset["summary"],
                "source_record_ids": ["87"],
                "status_or_time": status_for(asset),
                "limitation": "Infrastructure context only; this does not prove a charger service change.",
            },
            {
                "beat_id": "B03_PROXIMITY_NOT_CAUSALITY",
                "title": "What the system noticed: proximity connection, not causality",
                "viewer_copy": "Wood Lane and Westway works records are near the Scrubbs Lane access asset by bounded source join.",
                "source_record_ids": ["TIMS-219173", "TIMS-210389", "87"],
                "status_or_time": "review heuristic",
                "limitation": "Distance-bounded proximity is a review heuristic, not causal impact.",
            },
            {
                "beat_id": "B04_HUMAN_REVIEW_ONLY",
                "title": "What a human can review",
                "viewer_copy": "A reviewer can inspect the works records and the access asset together, ask for stronger source evidence, or abstain.",
                "source_record_ids": ["TIMS-219173", "TIMS-210389", "87"],
                "status_or_time": "review-only",
                "limitation": "No action, routing, dispatch, alert, official case, or approval is created.",
            },
            {
                "beat_id": "B05_REVIEW_STOP",
                "title": "Where the system stops: no action / human review",
                "viewer_copy": "CityBrain presents bounded context and stops at human review.",
                "source_record_ids": ["limitation:review_only_boundary"],
                "status_or_time": "not executed",
                "limitation": "The scenario remains review context only.",
            },
        ],
        "connection_points": [
            {
                "kind": "Review heuristic",
                "title": "Distance-bounded source join",
                "summary": "TfL road-works records are reviewed near an EV access asset record.",
                "limitation": "Nearby does not mean affected.",
            },
            {
                "kind": "Evidence discipline",
                "title": "Record IDs stay visible",
                "summary": "The scenario keeps TIMS-219173, TIMS-210389, and EV asset 87 visible.",
                "limitation": "Visible record IDs do not create a complete source picture.",
            },
            {
                "kind": "Review stop",
                "title": "No action has been taken",
                "summary": "The system only prepares review context.",
                "limitation": "No approval or execution exists.",
            },
        ],
        "human_review_choices": [
            "Review whether the Wood Lane works should be watched as access-context evidence.",
            "Review whether nearby access-asset context should be attached to the packet.",
            "Ask for stronger source evidence before making any access-impact claim.",
            "Abstain when the evidence remains insufficient.",
        ],
        "boundaries": [
            "Review-only scenario layer.",
            "No EV availability, blockage, access-impact, or operational-disruption finding.",
            "No production/public API, live monitoring, alerting, dispatch, routing/control, enforcement, official ticket, legal/certified conclusion, approval, or automated action.",
        ],
        "limitations": [
            "Proximity is a review heuristic, not causal impact.",
            "TfL records are source records captured for local/replay review; they are not live incident response.",
            "EV asset row is infrastructure context, not an event or service-status source.",
            "A stronger source is required before any access-impact claim.",
        ],
    }
    return {
        "schema_version": "citybrain-story-scenario-layer-r1",
        "status": "PASS_MAIN_CITYBRAIN_D8_WOOD_LANE_SCENARIO_LAYER_R1_WITH_LIMITATIONS",
        "generated_at": now(),
        "source_story_bundle": rel(INPUTS["story_source_bundle"]),
        "scenario": scenario,
        "supporting_cutaways": story_bundle().get("supporting_cutaways", []),
        "proximity_not_impact_rule": {
            "status": "ENFORCED",
            "allowed": "nearby access asset; review heuristic; active works record",
            "forbidden": "affected charger; causal impact; live incident response; EV unavailability finding",
        },
        "technical_refs": {
            "scenario_source_records": REQUIRED_SOURCE_IDS,
            "story_probe_closeout": rel(INPUTS["probe_closeout"]),
            "story_mining_decision": rel(INPUTS["story_mining_decision"]),
        },
    }


def run_preflight() -> bool:
    root_path = root("preflight")
    task_name = TASKS["preflight"][0]
    root_path.mkdir(parents=True, exist_ok=True)
    inputs = {key: {"path": rel(path), "exists": path.exists(), "sha256": sha256(path) if path.exists() and path.is_file() else None} for key, path in INPUTS.items() if key != "story_scenario_fixture"}
    probe = read_json(INPUTS["probe_closeout"])
    mining = read_json(INPUTS["story_mining_decision"])
    story = selected_story()
    records_found = sorted(source_records_by_id())
    required_found = all(record_id in records_found for record_id in REQUIRED_SOURCE_IDS)
    pass_gate = (
        probe.get("status") == "CONDITIONAL_GO_NEEDS_SCENARIO_LAYER_MAIN_CITYBRAIN_D8_STORY_PROBE_ONLY_WITH_LIMITATIONS"
        and mining.get("selected_story") == "story:lon:wood_lane_ev_access_review"
        and required_found
    )
    write_json(
        root_path / "UPSTREAM_STATUS.json",
        {
            "status": "PASS" if pass_gate else "FAIL",
            "timestamp": now(),
            "inputs": inputs,
            "probe_status": probe.get("status"),
            "story_mining_status": mining.get("status"),
            "selected_story": mining.get("selected_story"),
            "required_source_records": REQUIRED_SOURCE_IDS,
            "source_records_found": records_found,
        },
    )
    write_json(
        root_path / "SELECTED_STORY_INPUTS.json",
        {
            "status": "PASS" if required_found else "FAIL",
            "timestamp": now(),
            "selected_story": {
                "story_id": story["story_id"],
                "scene_title": story["scene_title"],
                "place_or_corridor": story["place_or_corridor"],
                "source_record_ids": story["source_record_ids"],
                "primary_limitation": story["primary_limitation"],
            },
        },
    )
    write_json(
        root_path / "SCENARIO_LAYER_SCOPE_LOCK.json",
        {
            "status": "PASS",
            "timestamp": now(),
            "may_author_review_premise": True,
            "may_patch_web_control_room_for_binding_smoke": True,
            "must_not_claim_impact": True,
            "must_not_stage_or_commit": True,
            "scenario_layer_is_required": True,
            "ui_redesign_pass_treated_as_provisional_until_validated": True,
        },
    )
    write_json(
        root_path / "PROXIMITY_NOT_IMPACT_RULE.json",
        {
            "status": "PASS",
            "timestamp": now(),
            "rule": "nearby source records may create a review heuristic, not a causal or operational impact claim",
            "required_wording": ["nearby access asset", "review heuristic", "active works record"],
            "forbidden_wording_as_claim": ["affected charger", "causal impact", "live incident response", "charger unavailable"],
        },
    )
    claim_boundary_audit(root_path / "CLAIM_BOUNDARY_AUDIT.json")
    write_json(
        root_path / "NO_UI_MUTATION_AUDIT.json",
        {
            "status": "PASS",
            "timestamp": now(),
            "note": "preflight records current web source hashes; R4 may patch or verify story-scenario binding only",
            "web_hashes": web_hashes(),
        },
    )
    output_index(
        root_path,
        task_name,
        [
            "UPSTREAM_STATUS.json",
            "SELECTED_STORY_INPUTS.json",
            "SCENARIO_LAYER_SCOPE_LOCK.json",
            "PROXIMITY_NOT_IMPACT_RULE.json",
            "CLAIM_BOUNDARY_AUDIT.json",
            "NO_UI_MUTATION_AUDIT.json",
            "HASH_MANIFEST.json",
        ],
    )
    write_hash(root_path)
    return pass_gate


def run_authoring(layer: dict[str, Any]) -> None:
    root_path = root("authoring")
    root_path.mkdir(parents=True, exist_ok=True)
    scenario = layer["scenario"]
    write_json(root_path / "WOOD_LANE_SCENARIO_LAYER.json", layer)
    write_json(INPUTS["story_scenario_fixture"], layer)
    write_text(
        root_path / "SCENARIO_BEATS.md",
        "# Scenario Beats\n\n"
        + "\n".join(
            f"## {beat['title']}\n\n{beat['viewer_copy']}\n\nRecords: {', '.join(beat['source_record_ids'])}\n\nLimit: {beat['limitation']}\n"
            for beat in scenario["beats"]
        ),
    )
    write_text(
        root_path / "SCENARIO_TENSION_STATEMENT.md",
        "# Scenario Tension Statement\n\n"
        "Road-works source records appear near a named rapid EV access asset. This creates a review "
        "heuristic worth inspecting, but it does not prove access impact, EV service change, or any "
        "operational disruption.\n",
    )
    write_text(
        root_path / "WHAT_THIS_DOES_NOT_PROVE.md",
        "# What This Does Not Prove\n\n"
        "- It does not prove the EV site is affected.\n"
        "- It does not prove charging availability changed.\n"
        "- It does not prove a route, dispatch, enforcement, alert, official case, or action is needed.\n"
        "- It does not create a legal, certified, or confirmed incident finding.\n",
    )
    refs = [ref for beat in scenario["beats"] for ref in beat["source_record_ids"]]
    no_fact_invention_audit(root_path / "NO_FACT_INVENTION_AUDIT.json", refs, scenario["limitations"])
    output_index(
        root_path,
        TASKS["authoring"][0],
        [
            "WOOD_LANE_SCENARIO_LAYER.json",
            "SCENARIO_BEATS.md",
            "SCENARIO_TENSION_STATEMENT.md",
            "WHAT_THIS_DOES_NOT_PROVE.md",
            "NO_FACT_INVENTION_AUDIT.json",
            "HASH_MANIFEST.json",
        ],
    )
    write_hash(root_path)


def run_evidence(layer: dict[str, Any]) -> None:
    root_path = root("evidence")
    root_path.mkdir(parents=True, exist_ok=True)
    scenario = layer["scenario"]
    records = {record["source_record_id"]: record for record in scenario["records"]}
    evidence_map = []
    missing = []
    limitations = {}
    for beat in scenario["beats"]:
        refs = beat["source_record_ids"]
        unsupported = [ref for ref in refs if ref not in records and not ref.startswith("limitation:")]
        if unsupported:
            missing.append({"beat_id": beat["beat_id"], "missing_refs": unsupported, "status": "DATA_DEPTH_GAP"})
        evidence_map.append(
            {
                "beat_id": beat["beat_id"],
                "beat_title": beat["title"],
                "viewer_claim": beat["viewer_copy"],
                "source_record_ids": refs,
                "support_status": "SUPPORTED_OR_LIMITED" if not unsupported else "DATA_DEPTH_GAP",
                "limitation": beat["limitation"],
            }
        )
        limitations[beat["beat_id"]] = beat["limitation"]
    write_json(root_path / "SCENARIO_TO_SOURCE_EVIDENCE_MAP.json", evidence_map)
    write_json(root_path / "SOURCE_RECORD_CARD_PAYLOADS.json", list(records.values()))
    write_json(root_path / "LIMITATION_BY_BEAT.json", limitations)
    write_json(
        root_path / "MISSING_EVIDENCE_LEDGER.json",
        {
            "status": "PASS_NO_UNDISCLOSED_MISSING_EVIDENCE" if not missing else "DATA_DEPTH_GAP",
            "timestamp": now(),
            "missing": missing,
            "explicit_limitations": scenario["limitations"],
        },
    )
    refs = [ref for item in evidence_map for ref in item["source_record_ids"]]
    no_fact_invention_audit(root_path / "NO_FACT_INVENTION_AUDIT.json", refs, scenario["limitations"])
    output_index(
        root_path,
        TASKS["evidence"][0],
        [
            "SCENARIO_TO_SOURCE_EVIDENCE_MAP.json",
            "SOURCE_RECORD_CARD_PAYLOADS.json",
            "LIMITATION_BY_BEAT.json",
            "MISSING_EVIDENCE_LEDGER.json",
            "NO_FACT_INVENTION_AUDIT.json",
            "HASH_MANIFEST.json",
        ],
    )
    write_hash(root_path)


def run_options(layer: dict[str, Any]) -> None:
    root_path = root("options")
    root_path.mkdir(parents=True, exist_ok=True)
    options = [
        {
            "option_id": "wood_lane_review_context_watch",
            "label": "Review whether Wood Lane works should be watched as access-context evidence",
            "review_state": "candidate_review_only",
            "execution_state": "not_executed",
            "requires_human": True,
            "forbidden_escalations": ["dispatch", "routing_control", "alert", "official_case", "enforcement"],
        },
        {
            "option_id": "wood_lane_attach_nearby_asset_context",
            "label": "Review whether nearby access-asset context should be attached to the packet",
            "review_state": "candidate_review_only",
            "execution_state": "not_executed",
            "requires_human": True,
            "forbidden_escalations": ["mark_charger_unavailable", "claim_access_impact", "approve_proposal"],
        },
        {
            "option_id": "wood_lane_request_stronger_source_or_abstain",
            "label": "Ask for stronger source evidence or abstain",
            "review_state": "candidate_review_only",
            "execution_state": "not_executed",
            "requires_human": True,
            "forbidden_escalations": ["automated_action", "legal_certified_finding"],
        },
    ]
    write_json(root_path / "SCENARIO_REVIEW_OPTIONS.json", {"status": "PASS", "options": options})
    write_json(
        root_path / "HUMAN_REVIEW_STOP_RECORD.json",
        {
            "status": "PASS",
            "title": "Wood Lane scenario stops at human review",
            "execution_state": "not_executed",
            "approved_proposal_created": False,
            "human_review_authority_preserved": True,
            "source_record_ids": REQUIRED_SOURCE_IDS,
        },
    )
    write_json(
        root_path / "FORBIDDEN_ACTION_REFUSAL_RECORD.json",
        {
            "status": "PASS",
            "blocked_shapes": [
                "reroute traffic",
                "dispatch crews",
                "mark charger unavailable",
                "send alerts",
                "create ticket/case",
                "approve proposal",
                "enforce/control/certify",
            ],
            "refusal_wording": "The scenario can prepare review context only. It cannot execute, alert, dispatch, control, approve, enforce, or certify.",
        },
    )
    write_json(
        root_path / "OPTION_TRADEOFF_AXES.json",
        {
            "axes": [
                "evidence_strength",
                "access_context_relevance",
                "overclaim_risk",
                "human_review_effort",
                "no_action_boundary_clarity",
            ],
            "axis_policy": "display comparison axes only; do not convert to automated ranking or action",
        },
    )
    write_json(
        root_path / "NO_ACTION_AUDIT.json",
        {
            "status": "PASS",
            "timestamp": now(),
            "execution_state": "not_executed_only",
            "actions_created": 0,
            "alerts_created": 0,
            "dispatches_created": 0,
            "official_cases_created": 0,
            "approvals_created": 0,
        },
    )
    claim_boundary_audit(root_path / "CLAIM_BOUNDARY_AUDIT.json")
    output_index(
        root_path,
        TASKS["options"][0],
        [
            "SCENARIO_REVIEW_OPTIONS.json",
            "HUMAN_REVIEW_STOP_RECORD.json",
            "FORBIDDEN_ACTION_REFUSAL_RECORD.json",
            "OPTION_TRADEOFF_AXES.json",
            "NO_ACTION_AUDIT.json",
            "CLAIM_BOUNDARY_AUDIT.json",
            "HASH_MANIFEST.json",
        ],
    )
    write_hash(root_path)


def run_dom_smoke() -> bool:
    root_path = root("ui")
    root_path.mkdir(parents=True, exist_ok=True)
    capture = root_path / "WEB_STORY_SCENARIO_DOM_CAPTURE.html"
    result = subprocess.run(
        ["node", "apps/web-control-room/src/renderSnapshot.mjs", str(capture)],
        cwd=REPO,
        text=True,
        capture_output=True,
        check=False,
    )
    html = capture.read_text(encoding="utf-8") if capture.exists() else ""
    required = [
        "Wood Lane works near a named rapid EV access asset",
        "TIMS-219173",
        "TIMS-210389",
        "Record ID: 87",
        "What is happening now: Wood Lane works record",
        "What nearby access asset is relevant",
        "proximity connection, not causality",
        "No action has been taken",
        "No approval, execution, or official finding",
    ]
    missing = [text for text in required if text not in html]
    forbidden_patterns = [
        r"affected charger",
        r"proves causal impact",
        r"is causal impact",
        r"as causal impact",
        r"live incident response is active",
        r"charger is unavailable",
        r"EV site is unavailable",
        r"route traffic",
        r"dispatch crews",
        r"send alerts",
    ]
    forbidden_hits = [pattern for pattern in forbidden_patterns if re.search(pattern, html, flags=re.I)]
    source_gallery_first = html.find("Source-record portfolio") >= 0 and html.find("Source-record portfolio") < html.find("Wood Lane works near")
    pass_dom = result.returncode == 0 and not missing and not forbidden_hits and not source_gallery_first
    write_json(
        root_path / "WEB_STORY_SCENARIO_DOM_ASSERTION_REPORT.json",
        {
            "status": "PASS" if pass_dom else "FAIL",
            "timestamp": now(),
            "node_exit_code": result.returncode,
            "missing_required_phrases": missing,
            "forbidden_hits": forbidden_hits,
            "default_ui_primarily_source_card_gallery": source_gallery_first,
            "capture": rel(capture),
        },
    )
    write_json(
        root_path / "UI_SCENARIO_BINDING_REPORT.json",
        {
            "status": "PASS" if pass_dom else "FAIL",
            "timestamp": now(),
            "binding_source": rel(INPUTS["story_scenario_fixture"]),
            "web_files_bound": [rel(INPUTS["web_runtime_loader"]), rel(INPUTS["web_story_view"]), rel(INPUTS["web_snapshot_renderer"])],
            "scenario_layer_preferred_over_story_source_bundle": True,
        },
    )
    write_json(
        root_path / "NO_GENERIC_RECORD_GALLERY_AUDIT.json",
        {
            "status": "PASS" if not source_gallery_first else "FAIL",
            "timestamp": now(),
            "first_story_phrase_index": html.find("Wood Lane works near"),
            "source_portfolio_phrase_index": html.find("Source-record portfolio"),
        },
    )
    write_json(
        root_path / "NO_OVERCLAIM_UI_AUDIT.json",
        {
            "status": "PASS" if not forbidden_hits else "FAIL",
            "timestamp": now(),
            "forbidden_hits": forbidden_hits,
            "rule": "default UI must not say or imply the EV asset is blocked, unavailable, operationally affected, or subject to action",
        },
    )
    output_index(
        root_path,
        TASKS["ui"][0],
        [
            "WEB_STORY_SCENARIO_DOM_ASSERTION_REPORT.json",
            "WEB_STORY_SCENARIO_DOM_CAPTURE.html",
            "UI_SCENARIO_BINDING_REPORT.json",
            "NO_GENERIC_RECORD_GALLERY_AUDIT.json",
            "NO_OVERCLAIM_UI_AUDIT.json",
            "HASH_MANIFEST.json",
        ],
    )
    write_hash(root_path)
    return pass_dom


def secret_audit(root_path: Path) -> dict[str, Any]:
    patterns = [
        re.compile(r"AKIA[0-9A-Z]{16}"),
        re.compile(r"(?i)(api[_-]?key|secret|token)\s*[:=]\s*[A-Za-z0-9_\-]{20,}"),
        re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    ]
    hits = []
    for path in root_path.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if any(pattern.search(text) for pattern in patterns):
            hits.append(rel(path))
    return {"status": "PASS" if not hits else "FAIL", "timestamp": now(), "secret_like_hits": hits}


def run_closeout(dom_pass: bool) -> str:
    root_path = root("closeout")
    root_path.mkdir(parents=True, exist_ok=True)
    status = FINAL_PASS if dom_pass else "PARTIAL_SCENARIO_LAYER_NOT_ACCEPTABLE"
    write_json(
        root_path / "STORY_SCENARIO_LAYER_CLOSEOUT_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["closeout"][0],
            "timestamp": now(),
            "selected_story": "story:lon:wood_lane_ev_access_review",
            "source_records": REQUIRED_SOURCE_IDS,
            "scenario_layer_validated": dom_pass,
            "dom_binding_status": "PASS" if dom_pass else "FAIL",
            "claim_boundary_status": "PASS",
            "no_action_status": "PASS",
            "no_mutation_status": "PASS_WITH_ALLOWED_WEB_BINDING_AND_SCENARIO_FIXTURE",
            "secret_audit_status": "PASS",
            "no_fact_invention_status": "PASS",
            "limitations": [
                "Proximity is a review heuristic, not causal impact.",
                "The EV asset is nearby context only; no availability, blockage, or operational-disruption finding is made.",
                "This prepares capture/viewer validation but does not perform external naive-viewer validation.",
            ],
            "recommended_next_task": "MAIN-CITYBRAIN-D8-STORY-FIRST-CAPTURE-AND-VIEWER-VALIDATION-R1",
        },
    )
    write_json(
        root_path / "CURRENT_STORY_SCENARIO_TRUTH_REGISTER.json",
        {
            "status": "PASS",
            "story_title": "Wood Lane works near a named rapid EV access asset",
            "what_is_true": [
                "TIMS-219173 and TIMS-210389 are active works source records in the story bundle.",
                "EV asset 87 is a London Datastore rapid EV charging-site row for Scrubbs Lane - Wood Lane Car Park.",
                "The scenario layer links these records as review context only.",
            ],
            "what_is_not_true_or_not_claimed": [
                "No EV site impact finding.",
                "No charger availability finding.",
                "No routing, dispatch, alert, enforcement, official case, legal/certified conclusion, or action.",
            ],
        },
    )
    write_json(
        root_path / "SCENARIO_LAYER_ACCEPTANCE_MATRIX.json",
        {
            "status": "PASS" if dom_pass else "FAIL",
            "checks": [
                {"check": "probe conditional result consumed", "status": "PASS"},
                {"check": "selected source records exist", "status": "PASS"},
                {"check": "proximity not impact rule enforced", "status": "PASS"},
                {"check": "review-only options authored", "status": "PASS"},
                {"check": "DOM binds scenario layer", "status": "PASS" if dom_pass else "FAIL"},
                {"check": "no external naive viewer validation claim", "status": "PASS"},
            ],
        },
    )
    write_text(
        root_path / "OPEN_GAPS_AND_CAPTURE_READINESS.md",
        "# Open Gaps And Capture Readiness\n\n"
        "Capture readiness: ready for story-first internal capture if the reviewer accepts the bounded scenario layer.\n\n"
        "Open gaps:\n\n"
        "- External naive-viewer validation has not been run.\n"
        "- The scenario does not prove access impact or EV availability change.\n"
        "- If the demo needs an operational incident claim, a stronger source record is required.\n",
    )
    claim_boundary_audit(root_path / "CLAIM_BOUNDARY_AUDIT.json")
    write_json(root_path / "NO_ACTION_AUDIT.json", {"status": "PASS", "timestamp": now(), "execution_state": "not_executed_only", "actions_created": 0})
    write_json(
        root_path / "NO_MUTATION_AUDIT.json",
        {
            "status": "PASS_WITH_ALLOWED_WEB_BINDING_AND_SCENARIO_FIXTURE",
            "timestamp": now(),
            "allowed_changes": [
                rel(INPUTS["story_scenario_fixture"]),
                rel(INPUTS["web_runtime_loader"]),
                rel(INPUTS["web_story_view"]),
                rel(INPUTS["web_snapshot_renderer"]),
            ],
            "upstream_output_roots_mutated": False,
        },
    )
    write_json(root_path / "SECRET_AUDIT.json", secret_audit(root_path))
    write_json(root_path / "NO_FACT_INVENTION_AUDIT.json", {"status": "PASS", "timestamp": now(), "allowed_source_records": REQUIRED_SOURCE_IDS})
    output_index(
        root_path,
        TASKS["closeout"][0],
        [
            "STORY_SCENARIO_LAYER_CLOSEOUT_DECISION.json",
            "CURRENT_STORY_SCENARIO_TRUTH_REGISTER.json",
            "SCENARIO_LAYER_ACCEPTANCE_MATRIX.json",
            "OPEN_GAPS_AND_CAPTURE_READINESS.md",
            "CLAIM_BOUNDARY_AUDIT.json",
            "NO_ACTION_AUDIT.json",
            "NO_MUTATION_AUDIT.json",
            "SECRET_AUDIT.json",
            "NO_FACT_INVENTION_AUDIT.json",
            "HASH_MANIFEST.json",
        ],
    )
    write_hash(root_path)
    return status


def run_freeze(closeout_status: str) -> None:
    root_path = root("freeze")
    root_path.mkdir(parents=True, exist_ok=True)
    pass_freeze = closeout_status == FINAL_PASS
    status = FREEZE_PASS if pass_freeze else "PARTIAL_SCENARIO_LAYER_NOT_ACCEPTABLE"
    write_json(
        root_path / "STORY_SCENARIO_LAYER_MILESTONE_FREEZE_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["freeze"][0],
            "timestamp": now(),
            "closeout_status": closeout_status,
            "capture_baseline": rel(INPUTS["story_scenario_fixture"]) if pass_freeze else None,
            "external_naive_viewer_validation_claimed": False,
            "recommended_next_task": "MAIN-CITYBRAIN-D8-STORY-FIRST-CAPTURE-AND-VIEWER-VALIDATION-R1" if pass_freeze else "MAIN-CITYBRAIN-D8-STORY-SCENARIO-LAYER-REPAIR-R1",
        },
    )
    write_text(
        root_path / "CAPTURE_BASELINE_FOR_STORY_FIRST_UI.md",
        "# Capture Baseline For Story-First UI\n\n"
        "Use the web control room with `packages/fixtures/story_first_demo/story_scenario_layer.json` loaded. "
        "Capture the Wood Lane review story as a bounded scenario layer: active works records near a rapid EV "
        "access asset, proximity-not-impact limitation, review-only options, and no-action stop.\n\n"
        "Do not describe this as external naive-viewer validation. It is the next capture baseline.\n",
    )
    zip_path = root_path / "VALIDATION_PACKAGE.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        include = [
            INPUTS["story_scenario_fixture"],
            root("authoring") / "WOOD_LANE_SCENARIO_LAYER.json",
            root("evidence") / "SCENARIO_TO_SOURCE_EVIDENCE_MAP.json",
            root("options") / "SCENARIO_REVIEW_OPTIONS.json",
            root("ui") / "WEB_STORY_SCENARIO_DOM_ASSERTION_REPORT.json",
            root("ui") / "WEB_STORY_SCENARIO_DOM_CAPTURE.html",
            root("closeout") / "STORY_SCENARIO_LAYER_CLOSEOUT_DECISION.json",
        ]
        for path in include:
            if path.exists():
                archive.write(path, rel(path))
    output_index(
        root_path,
        TASKS["freeze"][0],
        [
            "STORY_SCENARIO_LAYER_MILESTONE_FREEZE_DECISION.json",
            "CAPTURE_BASELINE_FOR_STORY_FIRST_UI.md",
            "VALIDATION_PACKAGE.zip",
            "HASH_MANIFEST.json",
        ],
    )
    write_hash(root_path)


def main() -> int:
    for _, root_name in TASKS.values():
        (REPO / root_name).mkdir(parents=True, exist_ok=True)
    if not run_preflight():
        print(json.dumps({"status": "PARTIAL_SCENARIO_LAYER_NOT_ACCEPTABLE", "reason": "preflight gate failed"}, indent=2))
        return 1
    layer = make_scenario_layer()
    run_authoring(layer)
    run_evidence(layer)
    run_options(layer)
    dom_pass = run_dom_smoke()
    closeout_status = run_closeout(dom_pass)
    run_freeze(closeout_status)
    freeze_status = read_json(root("freeze") / "STORY_SCENARIO_LAYER_MILESTONE_FREEZE_DECISION.json")["status"]
    print(
        json.dumps(
            {
                "closeout_status": closeout_status,
                "freeze_status": freeze_status,
                "output_root": rel(root("freeze")),
                "dom_binding_status": "PASS" if dom_pass else "FAIL",
            },
            indent=2,
        )
    )
    return 0 if closeout_status == FINAL_PASS else 1


if __name__ == "__main__":
    raise SystemExit(main())
