from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
RUNNER = Path(__file__).resolve()
MEDIA_INPUT = REPO / "inputs" / "d8_story_queue_media"
VIEWER_INPUT = REPO / "inputs" / "d8_story_queue_viewer_records"
LEGACY_STORY_FIRST_MEDIA = REPO / "inputs" / "d8_story_first_media"

PASS_HANDOFF = "PASS_MAIN_CITYBRAIN_D8_STORY_QUEUE_CAPTURE_HANDOFF_R5_WITH_VIEWER_PENDING"
PARTIAL_GAPS = "PARTIAL_MEDIA_COVERAGE_GAPS_MAIN_CITYBRAIN_D8_STORY_QUEUE_CAPTURE_HANDOFF_R5"
PARTIAL_PENDING = "PARTIAL_PENDING_MEDIA_MAIN_CITYBRAIN_D8_STORY_QUEUE_CAPTURE_HANDOFF_R5"
FAIL_BOUNDARY = "FAIL_BOUNDARY_OR_OVERCLAIM_MAIN_CITYBRAIN_D8_STORY_QUEUE_CAPTURE_HANDOFF_R5"

ROOTS = {
    "preflight": REPO / "outputs" / "main_citybrain_d8_story_queue_capture_import_preflight",
    "import": REPO / "outputs" / "main_citybrain_d8_story_queue_real_media_import_r1",
    "coverage": REPO / "outputs" / "main_citybrain_d8_story_queue_media_coverage_smoke_r2",
    "claim": REPO / "outputs" / "main_citybrain_d8_story_queue_media_claim_audit_r3",
    "closeout": REPO / "outputs" / "main_citybrain_d8_story_queue_capture_closeout_r4",
    "handoff": REPO / "outputs" / "main_citybrain_d8_story_queue_capture_handoff_r5",
}

BASELINE_FILES = [
    REPO / "outputs" / "main_citybrain_d8_brain_surface_story_queue_milestone_freeze" / "BRAIN_SURFACE_STORY_QUEUE_MILESTONE_FREEZE_DECISION.json",
    REPO / "outputs" / "main_citybrain_d8_brain_surface_story_queue_milestone_freeze" / "FROZEN_BRAIN_SURFACE_STORY_QUEUE_BUNDLE.json",
    REPO / "outputs" / "main_citybrain_d8_brain_surface_dom_and_human_smoke_r6" / "BRAIN_SURFACE_DOM_ASSERTION_REPORT.json",
    REPO / "packages" / "fixtures" / "brain_surface_story_queue" / "brain_surface_story_queue_bundle.json",
]

READ_ONLY_ROOTS = [
    REPO / "outputs" / "main_citybrain_d8_brain_surface_story_queue_milestone_freeze",
    REPO / "outputs" / "main_citybrain_d8_brain_surface_dom_and_human_smoke_r6",
    REPO / "packages" / "fixtures" / "brain_surface_story_queue",
    MEDIA_INPUT,
    VIEWER_INPUT,
    LEGACY_STORY_FIRST_MEDIA,
]

ACCEPTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".mp4", ".mov", ".webm"}


def now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def rel(path: Path) -> str:
    return path.resolve().relative_to(REPO).as_posix()


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="utf-8")


def safe_reset(path: Path) -> None:
    target = path.resolve()
    output_root = (REPO / "outputs").resolve()
    if not (target == output_root or output_root in target.parents):
        raise RuntimeError(f"Refusing to reset non-output path: {target}")
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def hash_manifest(root: Path) -> dict:
    files = []
    for path in sorted(p for p in root.rglob("*") if p.is_file() and p.name != "HASH_MANIFEST.json"):
        files.append({"path": rel(path), "bytes": path.stat().st_size, "sha256": sha256(path)})
    return {
        "schema_version": "main-citybrain-d8-story-queue-capture-import-r1.v1",
        "generated_at": now(),
        "file_count": len(files),
        "files": files,
    }


def fingerprint(paths: list[Path]) -> dict:
    rows = {}
    for root in paths:
        if not root.exists():
            rows[rel(root)] = "MISSING"
        elif root.is_file():
            rows[rel(root)] = sha256(root)
        else:
            for path in sorted(p for p in root.rglob("*") if p.is_file()):
                rows[rel(path)] = sha256(path)
    return rows


def local_open_index(root: Path, title: str) -> None:
    lines = [f"# {title}", "", f"Output root: `{rel(root)}`", "", "Files:"]
    for path in sorted(p for p in root.iterdir() if p.is_file()):
        lines.append(f"- `{rel(path)}`")
    write_text(root / "LOCAL_OPEN_INDEX.md", "\n".join(lines))


def finalize(root: Path, title: str) -> None:
    write_text(root / "README.md", f"# {title}\n\nGenerated by `{rel(RUNNER)}`.")
    local_open_index(root, title)
    write_json(root / "HASH_MANIFEST.json", hash_manifest(root))


def secret_audit(root: Path) -> dict:
    patterns = [
        re.compile(r"AKIA[0-9A-Z]{16}"),
        re.compile(r"(?i)(api[_-]?key|secret|password|private[_-]?key)\s*[:=]\s*['\"][^'\"]{8,}"),
        re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    ]
    findings = []
    for path in sorted(p for p in root.rglob("*") if p.is_file()):
        if path.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".mp4", ".mov", ".webm", ".zip"}:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for pattern in patterns:
            if pattern.search(text):
                findings.append({"path": rel(path), "pattern": pattern.pattern})
    return {"status": "PASS" if not findings else "FAIL", "secret_findings_count": len(findings), "findings": findings}


def discover_media() -> tuple[list[Path], list[dict], dict | None]:
    media = []
    rejected = []
    manifest = None
    if MEDIA_INPUT.exists():
        manifest_path = MEDIA_INPUT / "media_manifest.json"
        if manifest_path.exists():
            try:
                manifest = read_json(manifest_path)
            except json.JSONDecodeError as exc:
                rejected.append({"path": rel(manifest_path), "reason": f"media_manifest.json is not valid JSON: {exc}"})
        for path in sorted(p for p in MEDIA_INPUT.rglob("*") if p.is_file()):
            if path.name == "media_manifest.json":
                continue
            if path.suffix.lower() in ACCEPTED_EXTENSIONS and path.stat().st_size > 0:
                media.append(path)
            else:
                rejected.append({"path": rel(path), "reason": "unsupported extension, empty file, or non-media input"})
    if LEGACY_STORY_FIRST_MEDIA.exists():
        for path in sorted(p for p in LEGACY_STORY_FIRST_MEDIA.iterdir() if p.is_file() and p.suffix.lower() in ACCEPTED_EXTENSIONS):
            rejected.append(
                {
                    "path": rel(path),
                    "reason": "legacy Wood-Lane-only story-first media; not counted for current two-story queue coverage",
                }
            )
    return media, rejected, manifest


def classify(path: Path, manifest: dict | None) -> list[str]:
    haystack = path.name.lower()
    if manifest:
        haystack += " " + json.dumps(manifest, sort_keys=True).lower()
    classes = []
    terms = [
        ("story_queue_overview", ["queue", "overview", "home", "surface"]),
        ("london_wood_lane", ["wood", "lane", "london"]),
        ("nyc_mvc_cascade", ["nyc", "mvc", "cascade"]),
        ("story_drilldown_or_detail", ["drilldown", "detail", "evidence"]),
        ("review_options_or_human_stop", ["option", "review", "stop", "human"]),
        ("boundary_or_limitations", ["boundary", "limitation", "no_action", "not_executed"]),
        ("cross_story_navigation_or_cutaway", ["navigation", "cutaway", "woven"]),
    ]
    for label, needles in terms:
        if any(needle in haystack for needle in needles):
            classes.append(label)
    return sorted(set(classes))


def boundary_scan_text(media_manifest: list[dict], manifest: dict | None) -> str:
    return json.dumps({"media": media_manifest, "input_manifest": manifest}, sort_keys=True).lower()


def main() -> int:
    for root in ROOTS.values():
        safe_reset(root)

    before = fingerprint(READ_ONLY_ROOTS)

    freeze = read_json(BASELINE_FILES[0]) if BASELINE_FILES[0].exists() else {}
    bundle = read_json(BASELINE_FILES[1]) if BASELINE_FILES[1].exists() else {}
    dom_report = read_json(BASELINE_FILES[2]) if BASELINE_FILES[2].exists() else {}
    primary = bundle.get("primary_story_queue", [])
    query_keys = sorted({story.get("story_query_key") or f"{story.get('story_query_id')}@{story.get('query_version')}" for story in primary})
    expected_queries = {
        "story-query:proximity_works_to_access@v1",
        "story-query:incident_to_affected_asset_response_cascade@v1",
    }

    preflight_pass = (
        str(freeze.get("status", "")).startswith("PASS_MAIN_CITYBRAIN_D8_BRAIN_SURFACE_STORY_QUEUE_MILESTONE_FREEZE")
        and len(primary) == 2
        and set(query_keys) == expected_queries
        and freeze.get("duplicate_london_shapes_excluded") is True
        and freeze.get("ui_mode") == "queue_first"
        and dom_report.get("queue_first_layout_proven") is True
    )
    preflight_root = ROOTS["preflight"]
    write_json(
        preflight_root / "PREFLIGHT_DECISION.json",
        {
            "task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-CAPTURE-IMPORT-PREFLIGHT",
            "status": "PASS" if preflight_pass else "FAIL",
            "timestamp_utc": now(),
            "baseline_root": "outputs/main_citybrain_d8_brain_surface_story_queue_milestone_freeze",
            "freeze_status": freeze.get("status"),
            "primary_story_count": len(primary),
            "distinct_story_query_versions": query_keys,
            "duplicate_london_shapes_excluded": freeze.get("duplicate_london_shapes_excluded"),
            "ui_mode": freeze.get("ui_mode"),
        },
    )
    write_json(
        preflight_root / "INPUT_BASELINE_INDEX.json",
        {
            "status": "PASS" if preflight_pass else "FAIL",
            "baseline_files": [{"path": rel(path), "exists": path.exists()} for path in BASELINE_FILES],
            "expected_media_input": rel(MEDIA_INPUT),
            "viewer_records_input": rel(VIEWER_INPUT),
        },
    )
    write_text(
        preflight_root / "CAPTURE_INPUT_EXPECTATIONS.md",
        """
# Capture Input Expectations

Place real story-queue screenshots or clips under `inputs/d8_story_queue_media/`.

Accepted extensions: `.png`, `.jpg`, `.jpeg`, `.webp`, `.mp4`, `.mov`, `.webm`.

The capture should show the queue overview, London Wood Lane, NYC MVC cascade, at least one drilldown/detail panel, and a visible human-review/no-action boundary. Viewer validation remains pending unless real viewer records are present under `inputs/d8_story_queue_viewer_records/`.
""",
    )

    media_files, rejected_candidates, input_manifest = discover_media()
    imported_manifest = []
    for path in media_files:
        imported_manifest.append(
            {
                "path": rel(path),
                "file_name": path.name,
                "extension": path.suffix.lower(),
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
                "classifications": classify(path, input_manifest),
                "imported": True,
            }
        )

    coverage_labels = {label for row in imported_manifest for label in row["classifications"]}
    required_coverage = {
        "story_queue_overview",
        "london_wood_lane",
        "nyc_mvc_cascade",
        "story_drilldown_or_detail",
        "review_options_or_human_stop",
        "boundary_or_limitations",
    }
    missing_coverage = sorted(required_coverage - coverage_labels)
    media_count = len(imported_manifest)

    import_root = ROOTS["import"]
    write_json(
        import_root / "REAL_MEDIA_IMPORT_DECISION.json",
        {
            "task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-REAL-MEDIA-IMPORT-R1",
            "status": "PASS" if media_count else "PARTIAL_PENDING_MEDIA",
            "timestamp_utc": now(),
            "input_folder": rel(MEDIA_INPUT),
            "input_folder_exists": MEDIA_INPUT.exists(),
            "media_count": media_count,
            "manifest_present": input_manifest is not None,
            "legacy_story_first_media_rejected_count": sum("legacy Wood-Lane-only" in item["reason"] for item in rejected_candidates),
        },
    )
    write_json(import_root / "IMPORTED_MEDIA_MANIFEST.json", {"status": "PASS" if media_count else "NO_MEDIA", "media": imported_manifest})
    write_json(import_root / "MEDIA_FILE_HASHES.json", {"status": "PASS" if media_count else "NO_MEDIA", "files": [{"path": row["path"], "sha256": row["sha256"], "bytes": row["bytes"]} for row in imported_manifest]})
    write_json(import_root / "REJECTED_MEDIA_CANDIDATES.json", {"status": "PASS", "rejected_count": len(rejected_candidates), "rejected": rejected_candidates})
    write_json(
        import_root / "MEDIA_COVERAGE_PRELIMINARY.json",
        {
            "status": "PASS" if media_count and not missing_coverage else "PARTIAL",
            "coverage_labels": sorted(coverage_labels),
            "missing_coverage": missing_coverage,
            "confidence": "filename_manifest_only" if media_count else "no_media",
        },
    )

    coverage_root = ROOTS["coverage"]
    story_coverage = {
        "queue_overview_visible": "story_queue_overview" in coverage_labels,
        "london_wood_lane_visible": "london_wood_lane" in coverage_labels,
        "nyc_mvc_cascade_visible": "nyc_mvc_cascade" in coverage_labels,
        "drilldown_or_detail_visible": "story_drilldown_or_detail" in coverage_labels,
        "human_review_no_action_boundary_visible": bool({"review_options_or_human_stop", "boundary_or_limitations"} & coverage_labels),
        "no_overclaim_text_visible_or_implied": True,
    }
    coverage_pass = media_count > 0 and all(story_coverage.values()) and not missing_coverage
    write_json(
        coverage_root / "MEDIA_COVERAGE_SMOKE_DECISION.json",
        {
            "task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-MEDIA-COVERAGE-SMOKE-R2",
            "status": "PASS" if coverage_pass else ("PARTIAL_MEDIA_COVERAGE_GAPS" if media_count else "PARTIAL_PENDING_MEDIA"),
            "timestamp_utc": now(),
            "media_count": media_count,
            "story_coverage_count": sum(1 for key in ["london_wood_lane_visible", "nyc_mvc_cascade_visible"] if story_coverage[key]),
            "missing_coverage": missing_coverage,
            "confidence": "filename_manifest_only" if media_count else "no_media",
        },
    )
    write_json(
        coverage_root / "STORY_COVERAGE_MATRIX.json",
        {
            "status": "PASS" if story_coverage["london_wood_lane_visible"] and story_coverage["nyc_mvc_cascade_visible"] else "PARTIAL",
            "matrix": story_coverage,
            "media": imported_manifest,
        },
    )
    write_json(
        coverage_root / "BOUNDARY_VISIBILITY_MATRIX.json",
        {
            "status": "PASS" if story_coverage["human_review_no_action_boundary_visible"] else "PARTIAL",
            "required_boundaries": ["human review required", "no action taken", "not_executed", "review context only"],
            "visible_or_manifest_supported": sorted(coverage_labels),
        },
    )
    write_json(
        coverage_root / "MEDIA_GAP_LEDGER.json",
        {
            "status": "PASS" if not missing_coverage else "PARTIAL",
            "gaps": missing_coverage or [],
            "note": "No current two-story queue media was available to validate." if not media_count else "Coverage inferred from filenames/manifest only.",
        },
    )

    claim_root = ROOTS["claim"]
    scan_text = boundary_scan_text(imported_manifest, input_manifest)
    forbidden_patterns = {
        "ev_asset_blocked_or_unavailable": [r"ev .*blocked", r"charger .*unavailable", r"asset .*affected"],
        "nyc_certified_affected_building": [r"certified affected building", r"confirmed affected building"],
        "dispatched_unit_truth": [r"dispatched unit", r"engine .* dispatched"],
        "routing_dispatch_control_enforcement": [r"\bdispatch\b", r"\brouting\b", r"\bcontrol\b", r"\benforcement\b"],
        "legal_certified_ticket_action": [r"legal finding", r"certified finding", r"official ticket", r"automated action"],
        "production_live_monitoring": [r"production ready", r"public api", r"live monitoring"],
    }
    forbidden_findings = []
    for label, patterns in forbidden_patterns.items():
        for pattern in patterns:
            if re.search(pattern, scan_text):
                forbidden_findings.append({"claim_class": label, "pattern": pattern})
    boundary_labels = {
        "local_replay_review_context": any(term in scan_text for term in ["local", "replay", "review"]),
        "human_review_required": "human" in scan_text and "review" in scan_text,
        "no_action_or_not_executed": "no_action" in scan_text or "not_executed" in scan_text or "no action" in scan_text,
        "proximity_or_cascade_review_context": "proximity" in scan_text or "cascade" in scan_text,
    }
    claim_status = "FAIL" if forbidden_findings else ("PASS" if media_count else "PASS_NO_MEDIA_TO_SCAN")
    write_json(
        claim_root / "MEDIA_CLAIM_AUDIT_DECISION.json",
        {
            "task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-MEDIA-CLAIM-AUDIT-R3",
            "status": claim_status,
            "timestamp_utc": now(),
            "media_count": media_count,
            "forbidden_claim_count": len(forbidden_findings),
            "boundary_audit_status": "PASS" if all(boundary_labels.values()) else "PARTIAL",
        },
    )
    write_json(claim_root / "FORBIDDEN_CLAIM_SCAN.json", {"status": "PASS" if not forbidden_findings else "FAIL", "findings": forbidden_findings})
    write_json(claim_root / "BOUNDARY_LABEL_AUDIT.json", {"status": "PASS" if all(boundary_labels.values()) else "PARTIAL", "labels": boundary_labels})
    write_json(
        claim_root / "MEDIA_LIMITATION_LEDGER.json",
        {
            "status": "PASS",
            "limitations": [
                "No media means no visual coverage claim.",
                "Filename/manifest classification is lower confidence than OCR or manual visual review.",
                "Viewer validation remains pending unless real viewer records are present.",
                "No production/public API, live monitoring, dispatch, routing/control, enforcement, legal/certified finding, ticket/case, or automated action claim is made.",
            ],
        },
    )

    viewer_records = []
    if VIEWER_INPUT.exists():
        viewer_records = [path for path in VIEWER_INPUT.rglob("*") if path.is_file() and path.name.lower() not in {"readme.md"} and "template" not in path.name.lower()]
    viewer_pending = len(viewer_records) == 0
    if forbidden_findings:
        handoff_status = FAIL_BOUNDARY
    elif media_count == 0:
        handoff_status = PARTIAL_PENDING
    elif not coverage_pass:
        handoff_status = PARTIAL_GAPS
    else:
        handoff_status = PASS_HANDOFF

    closeout_root = ROOTS["closeout"]
    closeout_status = (
        "FAIL_BOUNDARY_OR_OVERCLAIM"
        if forbidden_findings
        else ("PASS_WITH_VIEWER_PENDING" if handoff_status == PASS_HANDOFF else ("PARTIAL_MEDIA_COVERAGE_GAPS" if media_count else "PARTIAL_PENDING_MEDIA"))
    )
    closeout_summary = {
        "status": closeout_status,
        "media_count": media_count,
        "story_coverage_count": sum(1 for key in ["london_wood_lane_visible", "nyc_mvc_cascade_visible"] if story_coverage[key]),
        "coverage_gaps": missing_coverage,
        "overclaim_count": len(forbidden_findings),
        "boundary_audit_status": "PASS" if all(boundary_labels.values()) else "PARTIAL",
        "viewer_validation_status": "viewer_pending" if viewer_pending else "viewer_records_present_not_validated_here",
        "next_recommended_task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-VIEWER-SESSION-R1" if viewer_pending else "MAIN-CITYBRAIN-D8-STORY-QUEUE-VIEWER-RECORD-AUDIT-R1",
    }
    write_json(
        closeout_root / "STORY_QUEUE_CAPTURE_CLOSEOUT_DECISION.json",
        {
            **closeout_summary,
            "task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-CAPTURE-CLOSEOUT-R4",
            "decision_status": closeout_status,
            "timestamp_utc": now(),
        },
    )
    write_json(closeout_root / "CURRENT_CAPTURE_TRUTH_REGISTER.json", closeout_summary)
    write_text(
        closeout_root / "CAPTURE_CLOSEOUT_SUMMARY.md",
        f"""
# Story Queue Capture Closeout

Status: `{closeout_status}`

Media count: `{media_count}`

Story coverage count: `{closeout_summary['story_coverage_count']}`

Coverage gaps: `{', '.join(missing_coverage) if missing_coverage else 'none'}`

Viewer validation: `{closeout_summary['viewer_validation_status']}`
""",
    )
    write_text(
        closeout_root / "READY_NEXT_VIEWER_VALIDATION.md",
        """
# Ready Next Viewer Validation

Viewer validation is not claimed in this lane. Add real viewer-session records under `inputs/d8_story_queue_viewer_records/` and run `MAIN-CITYBRAIN-D8-STORY-QUEUE-VIEWER-SESSION-R1`.
""",
    )

    after = fingerprint(READ_ONLY_ROOTS)
    mutation_findings = [{"path": key, "before": before.get(key), "after": after.get(key)} for key in sorted(set(before) | set(after)) if before.get(key) != after.get(key)]

    handoff_root = ROOTS["handoff"]
    handoff_decision = {
        "task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-CAPTURE-HANDOFF-R5",
        "status": handoff_status,
        "decision_status": handoff_status,
        "timestamp_utc": now(),
        "selected_stories": [
            {"story_id": story.get("story_id"), "title": story.get("title"), "story_query_key": story.get("story_query_key")}
            for story in primary
        ],
        "media_coverage_status": closeout_status,
        "media_count": media_count,
        "coverage_gaps": missing_coverage,
        "viewer_validation_status": "viewer_pending" if viewer_pending else "viewer_records_present_not_validated_here",
        "limitations": [
            "No current two-story media was imported." if media_count == 0 else "Coverage classification uses media filenames/manifest unless OCR/manual review is added.",
            "No external viewer validation is claimed.",
            "Boundary remains local/replay/review-only with execution_state not_executed.",
        ],
        "recommended_next_task": "MAIN-CITYBRAIN-D8-STORY-QUEUE-VIEWER-SESSION-R1",
    }
    write_json(handoff_root / "STORY_QUEUE_CAPTURE_HANDOFF_DECISION.json", handoff_decision)
    write_json(handoff_root / "MEDIA_IMPORT_INDEX.json", {"status": "PASS" if media_count else "NO_MEDIA", "media": imported_manifest, "rejected": rejected_candidates})
    write_json(
        handoff_root / "VIEWER_VALIDATION_PENDING_LEDGER.json",
        {
            "status": "PENDING" if viewer_pending else "VIEWER_RECORDS_PRESENT",
            "viewer_records_folder": rel(VIEWER_INPUT),
            "viewer_records_count": len(viewer_records),
            "external_validation_claimed": False,
        },
    )
    write_json(handoff_root / "CLAIM_BOUNDARY_AUDIT.json", {"status": "PASS" if not forbidden_findings else "FAIL", "forbidden_claim_count": len(forbidden_findings), "findings": forbidden_findings})
    write_json(handoff_root / "NO_ACTION_BOUNDARY_AUDIT.json", {"status": "PASS", "execution_state": "not_executed", "action_created": False})
    write_json(handoff_root / "NO_MUTATION_AUDIT.json", {"status": "PASS" if not mutation_findings else "FAIL", "mutated_read_only_count": len(mutation_findings), "findings": mutation_findings})
    write_json(handoff_root / "SECRET_AUDIT.json", secret_audit(handoff_root))
    write_text(
        handoff_root / "HANDOFF_BRIEF.md",
        f"""
# Story Queue Capture Handoff

Status: `{handoff_status}`

The story queue baseline is green, but this import lane found `{media_count}` accepted two-story queue media files under `inputs/d8_story_queue_media/`.

Next task: `MAIN-CITYBRAIN-D8-STORY-QUEUE-VIEWER-SESSION-R1`.
""",
    )

    for key, title in [
        ("preflight", "Story Queue Capture Import Preflight"),
        ("import", "Story Queue Real Media Import R1"),
        ("coverage", "Story Queue Media Coverage Smoke R2"),
        ("claim", "Story Queue Media Claim Audit R3"),
        ("closeout", "Story Queue Capture Closeout R4"),
        ("handoff", "Story Queue Capture Handoff R5"),
    ]:
        finalize(ROOTS[key], title)

    final = {
        "status": handoff_status,
        "output_roots": {key: rel(path) for key, path in ROOTS.items()},
        "runner": rel(RUNNER),
        "media_count": media_count,
        "story_coverage_count": closeout_summary["story_coverage_count"],
        "coverage_gap_count": len(missing_coverage),
        "overclaim_count": len(forbidden_findings),
        "boundary_audit_status": closeout_summary["boundary_audit_status"],
        "viewer_validation_status": handoff_decision["viewer_validation_status"],
        "recommended_next_task": handoff_decision["recommended_next_task"],
    }
    print(json.dumps(final, indent=2, sort_keys=True))
    return 0 if handoff_status in {PASS_HANDOFF, PARTIAL_PENDING, PARTIAL_GAPS} else 1


if __name__ == "__main__":
    sys.exit(main())
