#!/usr/bin/env python3
"""Run D8 story-first capture and viewer-validation lane.

This runner is intentionally strict about evidence. It validates the Wood Lane
story-first baseline, imports only real media/viewer files if present, and
returns partial states when those files are absent.
"""

from __future__ import annotations

import csv
import datetime as dt
import hashlib
import json
import re
import subprocess
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[1]

TASKS = {
    "preflight": ("MAIN-CITYBRAIN-D8-STORY-FIRST-CAPTURE-VALIDATION-PREFLIGHT", "outputs/main_citybrain_d8_story_first_capture_validation_preflight"),
    "media": ("MAIN-CITYBRAIN-D8-STORY-FIRST-REAL-MEDIA-IMPORT-R1", "outputs/main_citybrain_d8_story_first_real_media_import_r1"),
    "media_audit": ("MAIN-CITYBRAIN-D8-STORY-FIRST-MEDIA-CLAIM-AUDIT-R2", "outputs/main_citybrain_d8_story_first_media_claim_audit_r2"),
    "viewer": ("MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-IMPORT-R3", "outputs/main_citybrain_d8_story_first_viewer_session_import_r3"),
    "scoreboard": ("MAIN-CITYBRAIN-D8-STORY-FIRST-NAIVE-VIEWER-SCOREBOARD-R4", "outputs/main_citybrain_d8_story_first_naive_viewer_scoreboard_r4"),
    "closeout": ("MAIN-CITYBRAIN-D8-STORY-FIRST-CAPTURE-VIEWER-CLOSEOUT", "outputs/main_citybrain_d8_story_first_capture_viewer_closeout"),
    "handoff": ("MAIN-CITYBRAIN-D8-STORY-FIRST-CAPTURE-VIEWER-CERTIFIED-STATE-HANDOFF", "outputs/main_citybrain_d8_story_first_capture_viewer_certified_state_handoff"),
}

UPSTREAMS = {
    "scenario_freeze": REPO / "outputs" / "main_citybrain_d8_story_scenario_layer_milestone_freeze" / "STORY_SCENARIO_LAYER_MILESTONE_FREEZE_DECISION.json",
    "scenario_layer": REPO / "packages" / "fixtures" / "story_first_demo" / "story_scenario_layer.json",
    "story_source_bundle": REPO / "packages" / "fixtures" / "story_first_demo" / "story_source_bundle.json",
    "scenario_dom_report": REPO / "outputs" / "main_citybrain_d8_story_first_ui_scenario_binding_smoke_r4" / "WEB_STORY_SCENARIO_DOM_ASSERTION_REPORT.json",
    "scenario_dom_capture": REPO / "outputs" / "main_citybrain_d8_story_first_ui_scenario_binding_smoke_r4" / "WEB_STORY_SCENARIO_DOM_CAPTURE.html",
}

MEDIA_DIRS = [
    REPO / "inputs" / "d8_story_first_media",
    REPO / "inputs" / "d8_real_media",
    REPO / "captures" / "d8_story_first",
    REPO / "outputs" / "manual_d8_story_first_capture",
]

VIEWER_DIRS = [
    REPO / "inputs" / "d8_story_first_viewer_records",
    REPO / "inputs" / "d8_viewer_records",
    REPO / "viewer_records" / "d8_story_first",
]

MEDIA_EXTS = {".mp4", ".mov", ".webm", ".png", ".jpg", ".jpeg", ".html"}
VIEWER_EXTS = {".json", ".csv", ".md", ".txt"}
SOURCE_IDS = ["TIMS-219173", "TIMS-210389", "87"]
FREEZE_PASS = "PASS_MAIN_CITYBRAIN_D8_STORY_SCENARIO_LAYER_MILESTONE_FREEZE_WITH_LIMITATIONS"

BOUNDARY = [
    "local/replay/review/query context only",
    "no production/public API/live monitoring",
    "no alerting, dispatch, routing/control, enforcement, official ticket/case, or approval",
    "no legal/certified conclusion",
    "no automated action",
    "proximity is review heuristic only",
    "nearby EV asset is context only",
    "no claim the EV asset is blocked, unavailable, or affected",
]


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat()


def root(key: str) -> Path:
    return REPO / TASKS[key][1]


def rel(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_hash(root_path: Path) -> None:
    rows = []
    for path in sorted(root_path.rglob("*")):
        if path.is_file() and path.name != "HASH_MANIFEST.json":
            rows.append({"path": rel(path), "sha256": sha256(path), "bytes": path.stat().st_size})
    write_json(root_path / "HASH_MANIFEST.json", {"schema_version": "citybrain-hash-manifest-r1", "timestamp": now(), "file_count": len(rows), "files": rows})


def output_index(root_path: Path, title: str, artifacts: list[str]) -> None:
    write_text(root_path / "README.md", f"# {title}\n\nGenerated by `{rel(Path(__file__))}`.\n")
    lines = [f"# {title}", "", "## Artifacts", ""]
    lines.extend(f"- `{artifact}`" for artifact in artifacts)
    write_text(root_path / "LOCAL_OPEN_INDEX.md", "\n".join(lines) + "\n")


def input_row(path: Path) -> dict[str, Any]:
    return {"path": rel(path), "exists": path.exists(), "sha256": sha256(path) if path.exists() and path.is_file() else None}


def run_snapshot_capture(target: Path) -> dict[str, Any]:
    result = subprocess.run(
        ["node", "apps/web-control-room/src/renderSnapshot.mjs", str(target)],
        cwd=REPO,
        text=True,
        capture_output=True,
        check=False,
    )
    html = target.read_text(encoding="utf-8") if target.exists() else ""
    required = [
        "Wood Lane works near a named rapid EV access asset",
        "TIMS-219173",
        "TIMS-210389",
        "Record ID: 87",
        "proximity connection, not causality",
        "No action has been taken",
    ]
    missing = [item for item in required if item not in html]
    old_gallery = html.find("Source-record portfolio") >= 0 and html.find("Source-record portfolio") < html.find("Wood Lane works near")
    return {
        "status": "PASS" if result.returncode == 0 and not missing and not old_gallery else "FAIL",
        "node_exit_code": result.returncode,
        "stderr": result.stderr.strip(),
        "capture_path": rel(target),
        "missing_required_phrases": missing,
        "old_generic_record_gallery_first": old_gallery,
    }


def media_kind(path: Path) -> str:
    name = path.name.lower()
    if "operator" in name and path.suffix.lower() in {".mp4", ".mov", ".webm"}:
        return "operator_walkthrough"
    if "executive" in name and path.suffix.lower() in {".mp4", ".mov", ".webm"}:
        return "executive_walkthrough"
    if path.suffix.lower() == ".html" or "dom" in name:
        return "dom_capture"
    if path.suffix.lower() in {".png", ".jpg", ".jpeg"}:
        return "screenshot"
    if path.suffix.lower() in {".mp4", ".mov", ".webm"}:
        return "moment_clip"
    return "other"


def beat_map_for(path: Path) -> list[str]:
    name = path.name.lower()
    beats = []
    if any(token in name for token in ["wood", "works", "operator", "executive", "story"]):
        beats.append("B01 Wood Lane works record")
    if any(token in name for token in ["asset", "access", "ev", "nearby", "operator", "executive", "story"]):
        beats.append("B02 nearby access asset")
    if any(token in name for token in ["proximity", "causality", "operator", "executive", "story"]):
        beats.append("B03 proximity-not-causality")
    if any(token in name for token in ["review", "option", "operator", "executive", "story"]):
        beats.append("B04 human review choices")
    if any(token in name for token in ["stop", "action", "operator", "executive", "story"]):
        beats.append("B05 review stop/no action")
    return beats or ["B01 Wood Lane works record"]


def discover_media() -> list[Path]:
    files = []
    for folder in MEDIA_DIRS:
        if folder.exists():
            files.extend(path for path in folder.rglob("*") if path.is_file() and path.suffix.lower() in MEDIA_EXTS)
    return sorted(set(files))


def discover_viewer_files() -> list[Path]:
    files = []
    for folder in VIEWER_DIRS:
        if folder.exists():
            files.extend(path for path in folder.rglob("*") if path.is_file() and path.suffix.lower() in VIEWER_EXTS)
    return sorted(set(files))


def classify_media(files: list[Path]) -> list[dict[str, Any]]:
    rows = []
    for path in files:
        rows.append(
            {
                "path": rel(path),
                "filename": path.name,
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
                "media_type": media_kind(path),
                "mapped_story_beats": beat_map_for(path),
                "real_file_imported": True,
            }
        )
    return rows


def parse_viewer_json(path: Path) -> list[dict[str, Any]]:
    payload = read_json(path)
    if isinstance(payload, list):
        return [row for row in payload if isinstance(row, dict)]
    if isinstance(payload, dict) and "viewers" in payload and isinstance(payload["viewers"], list):
        return [row for row in payload["viewers"] if isinstance(row, dict)]
    if isinstance(payload, dict):
        return [payload]
    return []


def parse_viewer_csv(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def parse_viewer_text(path: Path) -> list[dict[str, Any]]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.strip():
        return []
    return [
        {
            "viewer_id": path.stem,
            "viewer_type": "unknown_text_record",
            "watched": "unknown",
            "understood_unaided": None,
            "identified_story_subject": text[:240],
            "identified_tension": "",
            "identified_boundary": "",
            "confusions": [],
            "source_file": rel(path),
        }
    ]


def import_viewer_records(files: list[Path]) -> list[dict[str, Any]]:
    records = []
    for path in files:
        try:
            if path.suffix.lower() == ".json":
                parsed = parse_viewer_json(path)
            elif path.suffix.lower() == ".csv":
                parsed = parse_viewer_csv(path)
            else:
                parsed = parse_viewer_text(path)
        except Exception as exc:  # noqa: BLE001
            records.append({"source_file": rel(path), "parse_error": str(exc), "usable": False})
            continue
        for row in parsed:
            row = dict(row)
            row.setdefault("source_file", rel(path))
            records.append(row)
    return records


def viewer_quality(record: dict[str, Any]) -> dict[str, Any]:
    required = [
        "viewer_id",
        "viewer_type",
        "watched",
        "understood_unaided",
        "identified_story_subject",
        "identified_tension",
        "identified_boundary",
        "confusions",
    ]
    missing = [key for key in required if key not in record or record.get(key) in (None, "")]
    return {
        "viewer_id": record.get("viewer_id") or record.get("id") or record.get("source_file"),
        "source_file": record.get("source_file"),
        "usable": not missing,
        "missing_fields": missing,
    }


def truthy(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "yes", "1", "y"}


def score_viewer(record: dict[str, Any]) -> dict[str, Any]:
    text = " ".join(str(record.get(key, "")) for key in ("identified_story_subject", "identified_tension", "identified_boundary", "confusions")).lower()
    subject = "wood lane" in text or "scrubbs lane" in text
    tension = "works" in text and ("access" in text or "ev" in text)
    proximity = ("not proof" in text) or ("not caus" in text) or ("heuristic" in text) or ("not impact" in text)
    boundary = ("human review" in text) or ("no action" in text) or ("not executed" in text)
    serious_misunderstanding = any(term in text for term in ["charger unavailable", "blocked charger", "citybrain dispatched", "route/control executed"])
    return {
        "viewer_id": record.get("viewer_id") or record.get("id") or record.get("source_file"),
        "understood_what_happened": truthy(record.get("understood_unaided")) or subject,
        "identified_specific_subject": subject,
        "identified_tension": tension,
        "identified_non_obvious_connection": "near" in text or "proximity" in text or "connect" in text,
        "understood_proximity_not_causality": proximity,
        "understood_human_review_stop": boundary,
        "noticed_no_action_boundary": "no action" in text or "not executed" in text,
        "identified_confusion_or_gap": bool(record.get("confusions")),
        "serious_claim_misunderstanding": serious_misunderstanding,
    }


def claim_scan_text(text: str) -> list[str]:
    patterns = [
        r"charger (is )?(blocked|unavailable|affected)",
        r"EV (asset|site|charger) (is )?(blocked|unavailable|affected)",
        r"caused an access impact",
        r"CityBrain (executed|dispatched|routed|alerted|enforced|approved|certified|created a case)",
        r"Kit runtime is live",
    ]
    return [pattern for pattern in patterns if re.search(pattern, text, flags=re.I)]


def secret_audit(root_path: Path) -> dict[str, Any]:
    patterns = [
        re.compile(r"AKIA[0-9A-Z]{16}"),
        re.compile(r"(?i)(api[_-]?key|secret|token)\s*[:=]\s*[A-Za-z0-9_\-]{20,}"),
        re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    ]
    hits = []
    for path in root_path.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if any(pattern.search(text) for pattern in patterns):
            hits.append(rel(path))
    return {"status": "PASS" if not hits else "FAIL", "timestamp": now(), "secret_like_hits": hits}


def run_preflight() -> bool:
    root_path = root("preflight")
    root_path.mkdir(parents=True, exist_ok=True)
    freeze = read_json(UPSTREAMS["scenario_freeze"]) if UPSTREAMS["scenario_freeze"].exists() else {}
    layer = read_json(UPSTREAMS["scenario_layer"]) if UPSTREAMS["scenario_layer"].exists() else {}
    scenario = layer.get("scenario", {})
    snapshot = run_snapshot_capture(root_path / "STORY_FIRST_PREFLIGHT_DOM_CAPTURE.html")
    source_ids = scenario.get("source_record_ids", [])
    pass_gate = freeze.get("status") == FREEZE_PASS and scenario.get("story_id") == "story:lon:wood_lane_ev_access_review" and all(item in source_ids for item in SOURCE_IDS) and snapshot["status"] == "PASS"
    write_json(
        root_path / "STORY_FIRST_CAPTURE_PREFLIGHT_DECISION.json",
        {
            "status": "PASS" if pass_gate else "FAIL",
            "task_name": TASKS["preflight"][0],
            "timestamp": now(),
            "freeze_status": freeze.get("status"),
            "selected_story": scenario.get("story_id"),
            "source_records": source_ids,
            "story_first_ui_baseline_status": snapshot["status"],
            "old_generic_record_gallery": snapshot["old_generic_record_gallery_first"],
        },
    )
    write_json(
        root_path / "CAPTURE_BASELINE_INDEX.json",
        {
            "status": "PASS" if snapshot["status"] == "PASS" else "FAIL",
            "timestamp": now(),
            "upstreams": {key: input_row(path) for key, path in UPSTREAMS.items()},
            "preflight_dom_capture": snapshot,
            "expected_media_dirs": [rel(path) for path in MEDIA_DIRS],
            "expected_viewer_dirs": [rel(path) for path in VIEWER_DIRS],
        },
    )
    write_json(
        root_path / "BOUNDARY_PREFLIGHT_AUDIT.json",
        {
            "status": "PASS",
            "timestamp": now(),
            "boundary": BOUNDARY,
            "execution_state": "not_executed_only",
        },
    )
    output_index(root_path, TASKS["preflight"][0], ["STORY_FIRST_CAPTURE_PREFLIGHT_DECISION.json", "CAPTURE_BASELINE_INDEX.json", "BOUNDARY_PREFLIGHT_AUDIT.json", "STORY_FIRST_PREFLIGHT_DOM_CAPTURE.html", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return pass_gate


def run_media_import() -> list[dict[str, Any]]:
    root_path = root("media")
    root_path.mkdir(parents=True, exist_ok=True)
    files = discover_media()
    rows = classify_media(files)
    status = "PASS" if rows else "PARTIAL_PENDING_STORY_FIRST_MEDIA"
    beat_rows = [{"media_path": row["path"], "mapped_story_beats": row["mapped_story_beats"]} for row in rows]
    write_json(
        root_path / "REAL_MEDIA_IMPORT_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["media"][0],
            "timestamp": now(),
            "real_media_count": len(rows),
            "searched_locations": [rel(path) for path in MEDIA_DIRS],
            "do_not_fabricate_media": True,
        },
    )
    write_json(root_path / "STORY_FIRST_MEDIA_MANIFEST.json", {"status": status, "media": rows})
    write_json(root_path / "MEDIA_TO_STORY_BEAT_MAP.json", {"status": status, "items": beat_rows})
    write_json(
        root_path / "MEDIA_MISSING_LEDGER.json",
        {
            "status": "OPEN" if not rows else "CLOSED",
            "missing_if_empty": [
                "wood_lane_operator_walkthrough.mp4",
                "m_story_wood_lane_works.png",
                "m_nearby_access_asset.png",
                "m_review_options_stop.png",
                "media_manifest.json",
            ]
            if not rows
            else [],
            "message": "No real story-first media files were found in the accepted input locations." if not rows else "Real media files imported.",
        },
    )
    output_index(root_path, TASKS["media"][0], ["REAL_MEDIA_IMPORT_DECISION.json", "STORY_FIRST_MEDIA_MANIFEST.json", "MEDIA_TO_STORY_BEAT_MAP.json", "MEDIA_MISSING_LEDGER.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return rows


def run_media_audit(media_rows: list[dict[str, Any]]) -> str:
    root_path = root("media_audit")
    root_path.mkdir(parents=True, exist_ok=True)
    if not media_rows:
        status = "PARTIAL_PENDING_STORY_FIRST_MEDIA"
        claim_hits: list[dict[str, Any]] = []
    else:
        claim_hits = []
        for row in media_rows:
            path = REPO / row["path"]
            if path.suffix.lower() in {".html", ".txt", ".md", ".json"}:
                hits = claim_scan_text(path.read_text(encoding="utf-8", errors="ignore"))
            else:
                hits = claim_scan_text(row["filename"])
            if hits:
                claim_hits.append({"path": row["path"], "hits": hits})
        status = "FAIL" if claim_hits else "PASS"
    write_json(
        root_path / "STORY_FIRST_MEDIA_CLAIM_AUDIT.json",
        {
            "status": status,
            "task_name": TASKS["media_audit"][0],
            "timestamp": now(),
            "media_count": len(media_rows),
            "overclaim_hits": claim_hits,
            "required_media_claims": [
                "review-only/human review required/no action taken",
                "proximity is review heuristic, not causality",
                "source record IDs or source-backed story evidence visible/referenced",
            ],
        },
    )
    write_json(root_path / "NO_ACTION_MEDIA_AUDIT.json", {"status": "PASS" if not claim_hits else "FAIL", "timestamp": now(), "execution_state": "not_executed_only", "media_count": len(media_rows)})
    write_json(
        root_path / "MEDIA_LIMITATION_VISIBILITY_REPORT.json",
        {
            "status": status,
            "media_count": len(media_rows),
            "limitation_visibility": "not auditable until real media exists" if not media_rows else "audited by filename/text/html where available",
        },
    )
    output_index(root_path, TASKS["media_audit"][0], ["STORY_FIRST_MEDIA_CLAIM_AUDIT.json", "NO_ACTION_MEDIA_AUDIT.json", "MEDIA_LIMITATION_VISIBILITY_REPORT.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status


def run_viewer_import() -> list[dict[str, Any]]:
    root_path = root("viewer")
    root_path.mkdir(parents=True, exist_ok=True)
    files = discover_viewer_files()
    records = import_viewer_records(files)
    quality = [viewer_quality(record) for record in records]
    usable = [record for record, report in zip(records, quality) if report["usable"]]
    status = "PASS" if usable else "PARTIAL_PENDING_STORY_FIRST_VIEWER_RECORDS"
    write_json(
        root_path / "VIEWER_SESSION_IMPORT_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["viewer"][0],
            "timestamp": now(),
            "viewer_file_count": len(files),
            "viewer_record_count": len(records),
            "usable_viewer_record_count": len(usable),
            "searched_locations": [rel(path) for path in VIEWER_DIRS],
            "do_not_fabricate_viewer_records": True,
        },
    )
    write_json(root_path / "VIEWER_SESSION_INDEX.json", {"status": status, "records": records})
    write_json(root_path / "VIEWER_RECORD_QUALITY_REPORT.json", {"status": status, "quality": quality})
    write_json(
        root_path / "VIEWER_MISSING_LEDGER.json",
        {
            "status": "OPEN" if not usable else "CLOSED",
            "missing_if_empty": ["viewer_001.json", "viewer_002.json", "viewer_sessions.csv"] if not usable else [],
            "message": "No usable external/non-builder viewer records were found." if not usable else "Usable viewer records imported.",
        },
    )
    output_index(root_path, TASKS["viewer"][0], ["VIEWER_SESSION_IMPORT_DECISION.json", "VIEWER_SESSION_INDEX.json", "VIEWER_RECORD_QUALITY_REPORT.json", "VIEWER_MISSING_LEDGER.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return usable


def run_scoreboard(viewer_records: list[dict[str, Any]]) -> str:
    root_path = root("scoreboard")
    root_path.mkdir(parents=True, exist_ok=True)
    scores = [score_viewer(record) for record in viewer_records]
    serious = [score for score in scores if score["serious_claim_misunderstanding"]]
    status = "PARTIAL_PENDING_STORY_FIRST_VIEWER_RECORDS" if not scores else ("NEEDS_UI_REMEDIATION" if serious else "PASS")
    write_json(root_path / "NAIVE_VIEWER_SCOREBOARD.json", {"status": status, "viewer_count": len(scores), "scores": scores})
    write_text(
        root_path / "VIEWER_COMPREHENSION_SUMMARY.md",
        "# Viewer Comprehension Summary\n\n"
        + (
            "No usable external/non-builder viewer records were available, so comprehension cannot be scored yet.\n"
            if not scores
            else f"Scored {len(scores)} viewer record(s). Serious misunderstandings: {len(serious)}.\n"
        ),
    )
    write_json(
        root_path / "VIEWER_CONFUSION_LEDGER.json",
        {
            "status": status,
            "confusions": [
                {"viewer_id": record.get("viewer_id"), "confusions": record.get("confusions", [])}
                for record in viewer_records
                if record.get("confusions")
            ],
            "serious_claim_misunderstandings": serious,
        },
    )
    output_index(root_path, TASKS["scoreboard"][0], ["NAIVE_VIEWER_SCOREBOARD.json", "VIEWER_COMPREHENSION_SUMMARY.md", "VIEWER_CONFUSION_LEDGER.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status


def run_closeout(media_rows: list[dict[str, Any]], media_audit_status: str, viewers: list[dict[str, Any]], scoreboard_status: str) -> str:
    root_path = root("closeout")
    root_path.mkdir(parents=True, exist_ok=True)
    if media_rows and viewers and media_audit_status == "PASS" and scoreboard_status == "PASS":
        status = "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_CLOSEOUT_WITH_LIMITATIONS"
    elif media_rows and not viewers:
        status = "PARTIAL_MEDIA_READY_VIEWER_PENDING"
    elif viewers and not media_rows:
        status = "PARTIAL_VIEWER_RECORDS_PRESENT_MEDIA_PENDING"
    else:
        status = "PARTIAL_PENDING_MEDIA_AND_VIEWER"
    write_json(
        root_path / "STORY_FIRST_CAPTURE_VIEWER_CLOSEOUT_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["closeout"][0],
            "timestamp": now(),
            "media_count": len(media_rows),
            "usable_viewer_record_count": len(viewers),
            "media_claim_audit_status": media_audit_status,
            "viewer_scoreboard_status": scoreboard_status,
            "external_validation_claimed": False,
            "live_media_capture_claimed": bool(media_rows),
            "recommended_next_task": "MAIN-CITYBRAIN-D8-STORY-FIRST-REAL-CAPTURE-R1" if not media_rows else "MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-R1",
        },
    )
    write_json(
        root_path / "CURRENT_STORY_FIRST_DEMO_TRUTH_REGISTER.json",
        {
            "status": status,
            "story": "Wood Lane works near Scrubbs Lane / Wood Lane EV access asset",
            "validated_baseline": True,
            "media_imported": bool(media_rows),
            "viewer_records_imported": bool(viewers),
            "truth": [
                "Scenario-layer UI baseline is green.",
                "No real capture media was found." if not media_rows else "Real capture media was imported.",
                "No usable non-builder viewer records were found." if not viewers else "Usable viewer records were imported.",
            ],
            "not_claimed": [
                "external naive viewer validation" if not viewers else None,
                "live media capture" if not media_rows else None,
                "EV asset blocked/unavailable/affected",
                "action, alert, dispatch, routing/control, enforcement, official case, approval, or legal/certified conclusion",
            ],
        },
    )
    write_text(
        root_path / "OPEN_GAPS_AND_NEXT_ACTIONS.md",
        "# Open Gaps And Next Actions\n\n"
        + ("- Add real Wood Lane story-first media under `inputs/d8_story_first_media/`.\n" if not media_rows else "")
        + ("- Add at least one real external/non-builder viewer record under `inputs/d8_story_first_viewer_records/`.\n" if not viewers else "")
        + "- Keep the Wood Lane scenario framed as proximity-not-impact and human-review-only.\n",
    )
    write_json(root_path / "CLAIM_BOUNDARY_AUDIT.json", {"status": "PASS", "timestamp": now(), "boundary": BOUNDARY})
    write_json(root_path / "NO_ACTION_AUDIT.json", {"status": "PASS", "timestamp": now(), "execution_state": "not_executed_only", "actions_created": 0})
    write_json(root_path / "NO_MUTATION_AUDIT.json", {"status": "PASS", "timestamp": now(), "upstream_outputs_mutated": False, "writes": [rel(root(key)) for key in TASKS]})
    write_json(root_path / "SECRET_AUDIT.json", secret_audit(root_path))
    output_index(root_path, TASKS["closeout"][0], ["STORY_FIRST_CAPTURE_VIEWER_CLOSEOUT_DECISION.json", "CURRENT_STORY_FIRST_DEMO_TRUTH_REGISTER.json", "OPEN_GAPS_AND_NEXT_ACTIONS.md", "CLAIM_BOUNDARY_AUDIT.json", "NO_ACTION_AUDIT.json", "NO_MUTATION_AUDIT.json", "SECRET_AUDIT.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status


def run_handoff(closeout_status: str, media_count: int, viewer_count: int) -> str:
    root_path = root("handoff")
    root_path.mkdir(parents=True, exist_ok=True)
    if closeout_status == "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_CLOSEOUT_WITH_LIMITATIONS":
        status = "PASS_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_CERTIFIED_STATE_HANDOFF_WITH_LIMITATIONS"
    elif media_count and not viewer_count:
        status = "PARTIAL_MEDIA_READY_VIEWER_PENDING_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_CERTIFIED_STATE_HANDOFF"
    elif not media_count and not viewer_count:
        status = "PARTIAL_PENDING_MEDIA_AND_VIEWER_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_CERTIFIED_STATE_HANDOFF"
    else:
        status = "PARTIAL_PENDING_MEDIA_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VIEWER_CERTIFIED_STATE_HANDOFF"
    write_json(
        root_path / "STORY_FIRST_CAPTURE_VIEWER_CERTIFIED_STATE_HANDOFF_DECISION.json",
        {
            "status": status,
            "task_name": TASKS["handoff"][0],
            "timestamp": now(),
            "closeout_status": closeout_status,
            "media_count": media_count,
            "usable_viewer_record_count": viewer_count,
            "external_validation_claimed": False,
            "live_media_capture_claimed": bool(media_count),
            "recommended_next_task": "MAIN-CITYBRAIN-D8-STORY-FIRST-REAL-CAPTURE-R1" if not media_count else "MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-R1",
        },
    )
    write_text(
        root_path / "CURRENT_CERTIFIED_STATE.md",
        "# Current Certified State\n\n"
        f"Status: `{status}`\n\n"
        "The Wood Lane story-first UI/scenario layer is validated as the capture baseline. "
        "This handoff does not claim real media capture or external naive-viewer validation unless corresponding real input records exist.\n",
    )
    write_json(
        root_path / "READY_NEXT_TRACKS.json",
        {
            "ready": [
                "MAIN-CITYBRAIN-D8-STORY-FIRST-REAL-CAPTURE-R1" if not media_count else "MAIN-CITYBRAIN-D8-STORY-FIRST-VIEWER-SESSION-R1"
            ],
            "blocked_until_inputs_exist": [
                "external viewer validation" if not viewer_count else None,
                "media claim validation" if not media_count else None,
            ],
        },
    )
    write_json(
        root_path / "DEFERRED_NOT_CLAIMED_LEDGER.json",
        {
            "not_claimed": [
                "external naive-viewer validation" if not viewer_count else None,
                "real media capture" if not media_count else None,
                "production/public API/live monitoring",
                "dispatch/routing/control/enforcement/official case/approval/legal-certified conclusion/automated action",
                "EV asset blocked, unavailable, or affected",
            ],
            "boundary": BOUNDARY,
        },
    )
    output_index(root_path, TASKS["handoff"][0], ["STORY_FIRST_CAPTURE_VIEWER_CERTIFIED_STATE_HANDOFF_DECISION.json", "CURRENT_CERTIFIED_STATE.md", "READY_NEXT_TRACKS.json", "DEFERRED_NOT_CLAIMED_LEDGER.json", "HASH_MANIFEST.json"])
    write_hash(root_path)
    return status


def main() -> int:
    for _, path in TASKS.values():
        (REPO / path).mkdir(parents=True, exist_ok=True)
    if not run_preflight():
        print(json.dumps({"status": "FAIL_MAIN_CITYBRAIN_D8_STORY_FIRST_CAPTURE_VALIDATION_PREFLIGHT"}, indent=2))
        return 1
    media_rows = run_media_import()
    media_audit_status = run_media_audit(media_rows)
    viewers = run_viewer_import()
    scoreboard_status = run_scoreboard(viewers)
    closeout_status = run_closeout(media_rows, media_audit_status, viewers, scoreboard_status)
    handoff_status = run_handoff(closeout_status, len(media_rows), len(viewers))
    print(
        json.dumps(
            {
                "handoff_status": handoff_status,
                "closeout_status": closeout_status,
                "media_count": len(media_rows),
                "usable_viewer_record_count": len(viewers),
                "output_root": rel(root("handoff")),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
